import { env } from "cloudflare:test";
import { expect, it } from "vitest";
import { compareSpotRecords, readSpotOriginal, retainSpotEvidence } from "@/services/spot-evidence";
import { performSpotCheck } from "@/services/spot-check";
import { mintCertificate } from "@/services/certificates";
import { KV_KEYS } from "@/lib/kv-keys";
import { sha256Hex } from "@/lib/idempotency";
import type { Env } from "@/types";
import type { SubjectRound } from "@/services/subject-history";
const testEnv = env as Env;
it("rejects edited, rehashed, missing and mismatched originals", async () => {
  const report = await performSpotCheck(testEnv, "integrity.example");
  const minted = await mintCertificate(testEnv, {itemId:"spot_check", attests:report.evidence_hash});
  const id = minted.certificate.cert_id;
  await retainSpotEvidence(testEnv, id, {kind:"spot_check",report});
  expect(await readSpotOriginal(testEnv,id,"integrity.example")).toEqual(report);
  expect(await readSpotOriginal(testEnv,id,"other.example")).toBeNull();
  const tampered = structuredClone(report);
  tampered.record.host = "other.example";
  await testEnv.PATRONS.put(KV_KEYS.spotEvidence(id), JSON.stringify({kind:"spot_check",report:tampered}));
  expect(await readSpotOriginal(testEnv,id,"other.example")).toBeNull();
  tampered.signed_payload = JSON.stringify(tampered.record);
  tampered.evidence_hash = await sha256Hex(tampered.signed_payload);
  await testEnv.PATRONS.put(KV_KEYS.spotEvidence(id), JSON.stringify({kind:"spot_check",report:tampered}));
  expect(await readSpotOriginal(testEnv,id,"other.example")).toBeNull();
  await testEnv.PATRONS.delete(KV_KEYS.spotEvidence(id));
  expect(await readSpotOriginal(testEnv,id,"integrity.example")).toBeNull();
});
it("requires dated observations of the same endpoint and battery to name a change", async () => {
  const report = await performSpotCheck(testEnv, "compare.example");
  const row:SubjectRound = {sequence:1,week:"2026-W39",taken_at:"2026-09-24T00:00:00Z",observed_at:"2026-09-23T00:00:00Z",digest:"a",entry_url:"https://scvd.store/corpus/1.json",listed:true,probed:true,url:"https://compare.example/pay",battery:"test-v1",verdict:"ready",failed:[],advisories:[],coverage_suspect:false,note:"fixture"};
  report.record.history.timeline=[row];
  const newer=structuredClone(report);
  const next={...row,sequence:2,digest:"b",observed_at:"2026-09-25T00:00:00Z",verdict:"not_ready" as const};
  newer.record.history.timeline.push(next);
  expect(compareSpotRecords(report,newer)).toMatchObject({state:"changed",changed_fields:["verdict"]});
  next.url="https://compare.example/other";
  expect(compareSpotRecords(report,newer).state).toBe("not_comparable");
  next.url=row.url; next.battery="test-v2";
  expect(compareSpotRecords(report,newer).state).toBe("not_comparable");
  next.battery=row.battery; next.observed_at=row.observed_at!;
  expect(compareSpotRecords(report,newer).state).toBe("not_comparable");
  next.observed_at="";
  expect(compareSpotRecords(report,newer).state).toBe("not_comparable");
  newer.record.history.timeline=[];
  expect(compareSpotRecords(report,newer).state).toBe("not_comparable");
});
it("rejects a corrupted JCS signature even when the ordinary signed payload is untouched",async()=>{
  const report=await performSpotCheck(testEnv,"jcs-integrity.example");
  const cert=await mintCertificate(testEnv,{itemId:"spot_check",attests:report.evidence_hash});
  await retainSpotEvidence(testEnv,cert.certificate.cert_id,{kind:"spot_check",report});
  report.signature_jcs="00".repeat(64);
  await testEnv.PATRONS.put(KV_KEYS.spotEvidence(cert.certificate.cert_id),JSON.stringify({kind:"spot_check",report}));
  expect(await readSpotOriginal(testEnv,cert.certificate.cert_id,"jcs-integrity.example")).toBeNull();
});
