import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import { pathToFileURL } from 'node:url';
import { readSkillTree } from '../../scripts/skill-bundle.mjs';
import { skillFingerprint } from '../../scripts/lib/skill-tree.mjs';
const cli='/Users/seanrecord/.npm/_npx/3180710f30256dd9/node_modules/clawhub';
const {prepareSkillFilesForPublish}=await import(pathToFileURL(path.join(cli,'dist/cli/commands/publish.js')));
const {extractZipToDir}=await import(pathToFileURL(path.join(cli,'dist/skills.js')));
const require=createRequire(path.join(cli,'package.json'));
const {zipSync}=require('fflate');
const prepared=await prepareSkillFilesForPublish(path.resolve('registry/clawhub'));
const archive=zipSync(Object.fromEntries(prepared.map(f=>[f.relPath,f.bytes])));
const destination=fs.mkdtempSync('/private/tmp/scvd-clawhub-installed-');
await extractZipToDir(archive,destination);
const canonical=skillFingerprint(readSkillTree('skills/scvd-general-store'));
const installed=skillFingerprint(readSkillTree(destination));
if(canonical!==installed) throw Error('ClawHub packaged tree differs');
const report={cliVersion:JSON.parse(fs.readFileSync(path.join(cli,'package.json'))).version,files:prepared.map(f=>f.relPath),destination,canonicalSha256:canonical,installedSha256:installed,scope:'Executed ClawHub preparation and archive extraction locally; no auth, registry API, upload, or claim of remote installation.'};
fs.writeFileSync('research/package-skill-integration-2026-09-17/clawhub-installation.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
