import { Hono } from "hono";
import { escapeHtml } from "@/lib/sanitize";
import { renderSimplePage, wantsHtml } from "@/pages/simple-page";
import { listCorpus } from "@/services/corpus";
import { sourceRegister } from "@/services/source-liveness";
import {
  deriveLedger,
  type LedgerFinding,
  type WeekLedger,
} from "@/services/week-ledger";
import { jsonLdScript, organizationRef } from "@/lib/jsonld";
import { securityBlock } from "@/store/surface-contract";
import {
  INSTRUMENTS_OPENED,
  LEDGER_FOR_MONEY,
  LEDGER_FREE_FIRST,
  LEDGER_PROPOSITION,
} from "@/store/copy/instruments";
import type { HonoEnv } from "@/types";

/**
 * GET /ledger, /ledger/{week} and /ledger/{week}.json — one week of
 * everything this store observed, read as a research note rather than
 * shopped for across five tabs.
 *
 * THE ROOM EXISTS FOR A READER, not for an indexer. Every number here
 * is already public and already signed: the brief has served the
 * week's doors since S1, the changes feed has diffed week against week
 * since C6, and the corpus has held both since it shipped. What none
 * of them did was SAY ANYTHING. A reader wanting to know what happened
 * in a week had to open the brief for the counts, the changes feed for
 * the movement, /sources for whether the feeds were even answering,
 * /corrections for what we got wrong, and then do the joining
 * themselves — which is asking every reader to be an analyst.
 *
 * THE FINDINGS ARE MACHINE-DERIVED AND SAY SO. Every sentence in the
 * findings section is generated by a rule in services/week-ledger.ts
 * from fields it names in `derived_from`. That is a deliberate ceiling
 * on this page: it structures, it never interprets. The keeper's voice
 * is non-delegable and lives in the almanac, where a person writes it.
 *
 * PAGINATION IS BY SIGNED WEEK, and a week the chain does not hold is
 * a 404 that names the weeks it does (rule 52). Serving only the weeks
 * we looked would read as continuous coverage.
 */
export const ledgerRoutes = new Hono<HonoEnv>();

const LEDGER_CSS = `
.standfirst {
  font-size: 1.12rem; line-height: 1.65; color: var(--night-text);
  border-left: 2px solid var(--neon); padding-left: 1rem; margin: 1.25rem 0 1.75rem;
}
.weekbar {
  display: flex; flex-wrap: wrap; gap: 0.75rem; align-items: baseline;
  border-top: 1px solid var(--line); border-bottom: 1px solid var(--line);
  padding: 0.6rem 0; margin: 1.5rem 0; font-size: 0.85rem;
}
.weekbar .spacer { flex: 1 1 auto; }
.figures {
  display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
  gap: 0.75rem; margin: 1.5rem 0;
}
.figure {
  border: 1px solid var(--line); padding: 0.85rem 0.9rem; background: var(--card);
}
.figure .n {
  display: block; font-size: 1.75rem; line-height: 1.15; color: var(--neon);
  font-variant-numeric: tabular-nums;
}
.figure .of { display: block; font-size: 0.78rem; color: var(--night-faded); margin-top: 0.15rem; }
.figure .label {
  display: block; font-size: 0.8rem; color: var(--night-text); margin-top: 0.4rem;
}
.finding {
  border-left: 3px solid var(--line); padding: 0.1rem 0 0.1rem 1rem; margin: 1.25rem 0;
}
.finding.kind-finding { border-left-color: var(--teal); }
.finding.kind-gap { border-left-color: var(--neon); }
.finding.kind-note { border-left-color: var(--line); }
.finding .kind {
  display: inline-block; font-size: 0.68rem; letter-spacing: 0.08em;
  text-transform: uppercase; color: var(--night-faded); margin-bottom: 0.3rem;
}
.finding .headline { font-size: 1.02rem; color: var(--night-text); margin: 0 0 0.35rem; }
.finding .detail { font-size: 0.92rem; color: var(--night-text); }
.finding .from {
  display: block; font-size: 0.72rem; color: var(--night-faded); margin-top: 0.4rem;
}
.movement { width: 100%; border-collapse: collapse; margin: 1rem 0; }
.movement th, .movement td {
  text-align: left; padding: 0.35rem 0.6rem 0.35rem 0;
  border-bottom: 1px solid var(--line); font-size: 0.9rem;
}
.movement td.n { font-variant-numeric: tabular-nums; text-align: right; width: 5rem; }
.methods { border: 1px dashed var(--line); padding: 0.9rem 1rem; margin: 2rem 0 1rem; }
.methods h3 { margin-top: 0; }
.weeklist { line-height: 2; }
.weeklist a { display: inline-block; margin-right: 0.5rem; }
`;

const KIND_LABEL: Record<LedgerFinding["kind"], string> = {
  finding: "Finding",
  gap: "Gap — ours",
  note: "Note",
};

function num(value: number): string {
  return value.toLocaleString("en-US");
}

function figure(n: string, label: string, of?: string): string {
  return `<div class="figure"><span class="n">${escapeHtml(n)}</span>${
    of ? `<span class="of">${escapeHtml(of)}</span>` : ""
  }<span class="label">${escapeHtml(label)}</span></div>`;
}

function findingHtml(finding: LedgerFinding): string {
  return `<div class="finding kind-${escapeHtml(finding.kind)}">
    <span class="kind">${escapeHtml(KIND_LABEL[finding.kind])}</span>
    <p class="headline">${escapeHtml(finding.headline)}</p>
    <p class="detail">${escapeHtml(finding.detail)}</p>
    <span class="from">Derived from ${finding.derived_from
      .map((field) => `<code>${escapeHtml(field)}</code>`)
      .join(", ")}</span>
  </div>`;
}

function movementHtml(ledger: WeekLedger): string {
  const changes = ledger.changes;
  if (!changes) {
    return `<p class="menu-desc">No previous signed week to compare against, so
    there is no movement section. This is the first week the chain holds, or the
    week before it is one of the gaps named below.</p>`;
  }
  const rows: [string, number][] = [
    ["Appeared — named by a feed for the first time", changes.additions.length],
    ["Left — named by no feed this week", changes.removals.length],
    ["Recovered — payable again after not being", changes.recoveries.length],
    ["Regressed — was payable, is not", changes.regressions.length],
    ["Changed payment route", changes.changed_payment_routes.length],
    ["Changed price", changes.changed_prices.length],
    ["Changed defect state", changes.changed_defect_state.length],
  ];
  return `<table class="movement">
    <thead><tr><th>Against ${escapeHtml(changes.previous?.week ?? "—")}</th><th class="n">doors</th></tr></thead>
    <tbody>${rows
      .map(([label, count]) => `<tr><td>${escapeHtml(label)}</td><td class="n">${num(count)}</td></tr>`)
      .join("")}</tbody>
  </table>
  <p class="menu-meta">Denominators, because a movement count without them is
  a rate in disguise: ${num(changes.hosts_in_week)} doors this week,
  ${num(changes.hosts_in_previous)} last week, ${num(changes.hosts_in_both)} in both.</p>`;
}

function renderLedger(ledger: WeekLedger, base: string): string {
  const { brief } = ledger;
  const answered = brief.doors.payable + brief.doors.not_payable;
  const gaps = ledger.findings.filter((f) => f.kind === "gap");
  const rest = ledger.findings.filter((f) => f.kind !== "gap");

  const nav = `<div class="weekbar">
    ${
      ledger.previous_week
        ? `<a href="/ledger/${escapeHtml(ledger.previous_week)}">← ${escapeHtml(ledger.previous_week)}</a>`
        : `<span class="menu-meta">← no earlier week</span>`
    }
    <span class="spacer"></span>
    <span class="menu-meta">Sealed ${escapeHtml(ledger.taken_at)} · entry ${escapeHtml(String(ledger.sequence))}</span>
    <span class="spacer"></span>
    ${
      ledger.next_week
        ? `<a href="/ledger/${escapeHtml(ledger.next_week)}">${escapeHtml(ledger.next_week)} →</a>`
        : `<span class="menu-meta">no later week →</span>`
    }
  </div>`;

  const corrections = ledger.corrections_this_week.length
    ? `<section><h2>What we got wrong, this week</h2>
      ${ledger.corrections_this_week
        .map(
          (correction) => `<div class="finding kind-gap">
        <span class="kind">Correction · ${escapeHtml(correction.date)}</span>
        <p class="detail">${escapeHtml(correction.what_was_wrong)}</p>
        <span class="from">${escapeHtml(correction.how_long)}</span>
      </div>`,
        )
        .join("")}
      <p class="menu-meta">The full record, all of it, is at
      <a href="/corrections">/corrections</a>.</p></section>`
    : "";

  return `<section>
    <p class="standfirst">${escapeHtml(LEDGER_PROPOSITION)}</p>
    <p class="menu-desc">This is one week of the public x402 neighbourhood as
    this store's weekly round saw it — what we reached, what answered, what
    broke, what moved, and the part that matters most on a page like this:
    what we could not see. Every figure is a count over a single signed,
    hash-chained snapshot, and every sentence names the fields it came from.</p>
    ${nav}
  </section>

  <section><h2>The week in figures</h2>
  <div class="figures">
    ${figure(num(brief.doors.listed), "doors named by our feeds")}
    ${figure(num(brief.doors.probed), "knocked on", `of ${num(brief.doors.listed)} named`)}
    ${figure(num(brief.doors.payable), "a buyer could pay", answered ? `of ${num(answered)} that answered` : undefined)}
    ${figure(num(brief.doors.not_payable), "answered, not payable", answered ? `of ${num(answered)} that answered` : undefined)}
    ${figure(num(brief.doors.unreachable), "did not answer")}
    ${figure(num(brief.doors.offers_seen), "carried a parseable offer")}
  </div>
  <p class="menu-meta">Counts, each with the denominator it belongs to. No
  figure on this page is taken over the doors we did not knock on.</p>
  </section>

  <section><h2>Findings</h2>
  <p class="menu-desc">Generated from the week's own fields by a fixed rule,
  the same rule on every week. Structure, not interpretation — nothing here
  is a judgement about an operator, and nothing here is anybody's opinion.</p>
  ${rest.map(findingHtml).join("")}
  </section>

  <section><h2>What we could not see</h2>
  <p class="menu-desc">Counted against the instrument, on the same page as the
  findings, because a week's reading is exactly where a reader is most likely
  to mistake what we saw for what happened.</p>
  ${
    gaps.length
      ? gaps.map(findingHtml).join("")
      : `<p class="menu-desc">No gap fired this week: every named door was
      knocked on, our vantage held on every probe, the round did not flag its
      own coverage, every source answered, and the chain holds every week
      behind this one. Stated rather than omitted — a section that disappears
      when it is empty teaches a reader to read silence as completeness.</p>`
  }
  </section>

  <section><h2>What moved</h2>${movementHtml(ledger)}</section>

  ${
    brief.defects.length
      ? `<section><h2>Defects, by name</h2>
    <table class="movement">
      <thead><tr><th>defect</th><th class="n">doors</th></tr></thead>
      <tbody>${brief.defects
        .map(
          (defect) =>
            `<tr><td>${escapeHtml(defect.title)} <code>${escapeHtml(defect.id)}</code></td><td class="n">${num(defect.count)}</td></tr>`,
        )
        .join("")}</tbody>
    </table>
    <p class="menu-meta">A defect is a named check that failed, from the
    published vocabulary at <a href="/defects">/defects</a>. One door can carry
    several. A failure is a fact about one artifact at one moment, never a
    standing verdict on whoever runs it.</p></section>`
      : ""
  }

  <section><h2>Were the feeds answering?</h2>
  <p class="menu-desc">${num(ledger.sources.live)} live,
  ${num(ledger.sources.stale)} stale, ${num(ledger.sources.never_answered)}
  never answered, ${num(ledger.sources.unread)} named but not read.
  ${
    ledger.sources.not_answering.length
      ? `Quiet right now: ${escapeHtml(ledger.sources.not_answering.join(", "))}.`
      : "All of them, at the time this page was derived."
  }</p>
  <p class="menu-meta">Source liveness is derived from run history rather than
  maintained by hand, and is current as of this request, not as of the sealed
  week — the full register is at <a href="/sources">/sources</a>.</p>
  </section>

  ${corrections}

  <section class="methods">
    <h3>How to redo every number on this page</h3>
    <p class="menu-desc">${escapeHtml(ledger.how_to_rederive)}</p>
    <h3>What this is not</h3>
    <p class="menu-desc">${escapeHtml(ledger.what_this_is_not)}</p>
    <h3>What this costs</h3>
    <p class="menu-desc">${escapeHtml(LEDGER_FOR_MONEY)}</p>
    <p class="menu-meta">${escapeHtml(LEDGER_FREE_FIRST)}</p>
    <p class="menu-meta">The same ledger as JSON:
    <a href="/ledger/${escapeHtml(ledger.week)}.json"><code>${escapeHtml(base)}/ledger/${escapeHtml(ledger.week)}.json</code></a>.
    The signed snapshot behind it:
    <a href="/corpus/${escapeHtml(String(ledger.sequence))}.json"><code>/corpus/${escapeHtml(String(ledger.sequence))}.json</code></a>.
    Every door, alphabetical: <a href="/doors">/doors</a>.
    Where these numbers come from: <a href="/sources">/sources</a>.</p>
  </section>
  ${nav}
  ${jsonLdScript({
    "@context": "https://schema.org",
    "@type": "Report",
    name: `The Week's Ledger — ${ledger.week}`,
    description: LEDGER_PROPOSITION,
    url: `${base}/ledger/${ledger.week}`,
    creator: organizationRef(base),
    isAccessibleForFree: true,
    datePublished: ledger.taken_at,
    temporalCoverage: ledger.week,
    citation: `${base}/corpus/${ledger.sequence}.json`,
    license: "https://creativecommons.org/licenses/by/4.0/",
  })}`;
}

/**
 * THE FIVE ANSWERS (60.4) and the three sentences (60.2), on the index
 * twin and on every week's twin alike. A reader who lands on one week
 * should not have to walk up to the index to learn what the room is
 * or what it costs.
 */
function fiveAnswers(base: string) {
  return {
    what_this_is: LEDGER_PROPOSITION,
    proposition: LEDGER_PROPOSITION,
    price: LEDGER_FOR_MONEY,
    free_first: LEDGER_FREE_FIRST,
    opened: INSTRUMENTS_OPENED,
    how_to_call: {
      the_index: `GET ${base}/ledger for every week the chain holds, HTML or JSON by Accept.`,
      one_week: `GET ${base}/ledger/2026-W36 for the page, or ${base}/ledger/2026-W36.json for the same reading as JSON.`,
      the_findings: "Every entry in `findings` names the fields it was computed from in `derived_from`; fetch the snapshot it cites and recount.",
      subscribe: `The signed source is ${base}/corpus/latest.json, which carries ETag and Last-Modified for a conditional GET.`,
    },
    errors: {
      unknown_week: "A week the chain does not hold answers 404 with `known_weeks` naming the weeks it does. This store does not invent a baseline for a week it did not seal.",
      malformed_week: "Anything that is not a YYYY-Wnn week answers 404 rather than being guessed at.",
      no_weeks_yet: "With an empty chain the index answers 200 with an empty `weeks_held`. That is our age, not an error.",
    },
    security: securityBlock(base, {
      does_in_your_name: "Nothing. A GET here reads signed snapshots already published; no door is probed and nothing is fetched from anyone on your behalf.",
      stores: "Nothing about you. The porch counts a visit by surface, never by caller.",
    }),
  };
}

function notFound(week: string, known: string[], base: string) {
  return {
    error: `The chain holds no signed week named ${week}. This store does not invent a baseline for a week it did not seal.`,
    known_weeks: known,
    index: `${base}/ledger`,
  };
}

async function loadLedger(env: HonoEnv["Bindings"], week?: string) {
  const [records, register] = await Promise.all([
    listCorpus(env),
    sourceRegister(env).catch(() => null),
  ]);
  return deriveLedger(records, env.STORE_BASE_URL, register, week);
}

/** The index: every week the chain holds, newest first. */
ledgerRoutes.get("/ledger", async (c) => {
  const base = c.env.STORE_BASE_URL;
  const { ledger, known_weeks } = await loadLedger(c.env);
  if (!wantsHtml(c.req.header("Accept"), c.req.header("User-Agent"))) {
    return c.json({
      artifact: "week_ledger_index",
      ...fiveAnswers(base),
      weeks_held: known_weeks,
      latest: ledger ? `${base}/ledger/${ledger.week}.json` : null,
      what_this_is:
        "One reading per signed week: the doors, the movement, the defects and the gaps, with findings derived from the week's own fields. Derived at read from the signed chain, never stored.",
    });
  }
  const newest = [...known_weeks].reverse();
  return c.html(
    renderSimplePage({
      title: "The Week's Ledger",
      description:
        "One week of the observed x402 neighbourhood, read as a research note: what we reached, what answered, what moved, and what we could not see.",
      path: "/ledger",
      extraCss: LEDGER_CSS,
      bodyHtml: `<section>
        <p class="standfirst">${escapeHtml(LEDGER_PROPOSITION)}</p>
        <p class="menu-desc">One reading per signed week. Each page says what
        the round reached, what answered, what changed against the week before,
        and — on the same page, never a click away — what this instrument could
        not see.</p>
        <p class="menu-desc">${escapeHtml(LEDGER_FOR_MONEY)}</p>
        <p class="menu-meta">${escapeHtml(LEDGER_FREE_FIRST)}</p>
        ${
          ledger
            ? `<p class="menu-desc">The newest is
            <a href="/ledger/${escapeHtml(ledger.week)}">${escapeHtml(ledger.week)}</a>,
            sealed ${escapeHtml(ledger.taken_at)}.</p>`
            : `<p class="menu-desc">The chain holds no signed week yet, so there
            is nothing to read. That is a fact about this store's age, not about
            the ecosystem.</p>`
        }
      </section>
      <section><h2>Every week the chain holds</h2>
      <p class="weeklist">${
        newest.length
          ? newest
              .map(
                (week) =>
                  `<a href="/ledger/${escapeHtml(week)}"><code>${escapeHtml(week)}</code></a>`,
              )
              .join("")
          : "<span class='menu-meta'>None yet.</span>"
      }</p>
      <p class="menu-meta">A week absent from this list was never sealed —
      the round did not run, or ran and could not be sealed. Gaps are named
      on each week's page and on <a href="/corpus.json">/corpus.json</a>
      rather than left for a reader to notice. Whether the feeds behind these
      weeks are still answering: <a href="/sources">/sources</a>.</p></section>
      ${jsonLdScript({
        "@context": "https://schema.org",
        "@type": "Dataset",
        name: "The Week's Ledger",
        description: LEDGER_PROPOSITION,
        url: `${base}/ledger`,
        creator: organizationRef(base),
        isAccessibleForFree: true,
        conditionsOfAccess: "Free to read. No account, no key.",
        license: "https://creativecommons.org/licenses/by/4.0/",
        measurementTechnique:
          "Derived at read from the signed weekly corpus snapshots and the live source register; every finding names the fields it was computed from.",
        variableMeasured: [
          "doors named, knocked on, payable, not payable and unreachable, each with its denominator",
          "week-over-week movement: appeared, left, recovered, regressed",
          "named defect classes and their counts",
          "gaps counted against the observer: doors never probed, degraded vantage, suspect coverage",
        ],
      })}`,
    }),
  );
});

ledgerRoutes.get("/ledger/:file{[0-9]{4}-W[0-9]{2}\\.json}", async (c) => {
  const week = c.req.param("file").replace(/\.json$/, "");
  const { ledger, known_weeks } = await loadLedger(c.env, week);
  if (!ledger) {
    return c.json(notFound(week, known_weeks, c.env.STORE_BASE_URL), 404);
  }
  return c.json({ ...fiveAnswers(c.env.STORE_BASE_URL), ...ledger, weeks_held: known_weeks });
});

ledgerRoutes.get("/ledger/:week{[0-9]{4}-W[0-9]{2}}", async (c) => {
  const week = c.req.param("week");
  const base = c.env.STORE_BASE_URL;
  const { ledger, known_weeks } = await loadLedger(c.env, week);
  const html = wantsHtml(c.req.header("Accept"), c.req.header("User-Agent"));

  if (!ledger) {
    const body = notFound(week, known_weeks, base);
    if (!html) return c.json(body, 404);
    return c.html(
      renderSimplePage({
        title: `No ledger for ${week}`,
        description:
          "The chain holds no signed snapshot for that week, so there is no reading to serve. The weeks it does hold are listed.",
        extraCss: LEDGER_CSS,
        bodyHtml: `<section><p class="menu-desc">${escapeHtml(body.error)}</p>
        <p class="weeklist">${known_weeks
          .map(
            (held) =>
              `<a href="/ledger/${escapeHtml(held)}"><code>${escapeHtml(held)}</code></a>`,
          )
          .join("")}</p></section>`,
      }),
      404,
    );
  }

  if (!html) return c.json({ ...fiveAnswers(base), ...ledger, weeks_held: known_weeks });
  return c.html(
    renderSimplePage({
      title: `The Week's Ledger — ${ledger.week}`,
      description: `What this store's weekly round observed in ${ledger.week}: doors reached, doors payable, what moved, and what the instrument could not see.`,
      path: `/ledger/${ledger.week}`,
      extraCss: LEDGER_CSS,
      bodyHtml: renderLedger(ledger, base),
    }),
  );
});
