import { currentWeekKey } from "@/lib/kv-keys";
import { CORRECTIONS, type Correction } from "@/store/corrections";
import { deriveChanges, type WeekChanges } from "@/services/corpus-changes";
import { deriveWeeklyBrief, type WeeklyBrief } from "@/services/weekly-brief";
import { missingWeeks } from "@/services/ward-heartbeat";
import type { CorpusRecord } from "@/services/corpus";
import type { SourceRegister } from "@/services/source-liveness";

/**
 * THE WEEK'S LEDGER — one week of everything this store observed,
 * summarised with its findings, at an address that never changes
 * (the keeper's ask, 2026-09-04: "pull all that data together in an
 * aesthetic and human readable snapshot, almost as publishing
 * research").
 *
 * WHAT WAS ALREADY THERE, because the gap was narrower than it looked
 * and saying so keeps this honest. The corpus has frozen a signed,
 * hash-chained, Bitcoin-anchored snapshot every week since it shipped.
 * `/corpus/brief` renders one week's doors. `/corpus/changes/{week}`
 * diffs a week against the one before it. `/corpus/month` groups them.
 * Pagination by week was not missing; it was thorough.
 *
 * WHAT WAS MISSING WAS THE READING. Every one of those surfaces answers
 * one question well and leaves the reader to hold five tabs open and do
 * the joining themselves. Nothing said, in one place and in sentences:
 * here is what happened this week, here is what it means, here is what
 * we could not see, and here is where every number came from. A
 * measurement project that publishes only tables is asking its readers
 * to be its analysts.
 *
 * SO THE LEDGER DERIVES, NEVER STORES. Every field is read at request
 * time out of the signed chain and the live registers, so it cannot
 * drift from what was sealed — the same discipline as the changes feed,
 * for the same reason. A ledger cached at write time would be a sixth
 * number that can disagree with the other five.
 *
 * AND THE FINDINGS ARE DERIVED TOO, which is the part that needed care.
 * A "finding" here is not commentary and never an opinion about an
 * operator: it is a sentence whose every number came from a field named
 * in `derived_from`, generated by a rule that runs the same way on
 * every week. Nothing in this file invents a word about anybody. The
 * keeper's voice is non-delegable and lives in the almanac; the machine
 * structures, never interprets.
 *
 * THE GAPS RIDE THE SAME PAGE AS THE FINDINGS. That is the whole house
 * discipline, and here it is load-bearing twice over: a week's reading
 * is exactly the artifact where a reader is most likely to mistake
 * "what we saw" for "what happened".
 */

export type FindingKind =
  /** Something the week's own numbers say. */
  | "finding"
  /** A limit of the instrument, counted against us. */
  | "gap"
  /** Context a reader needs to not misread a number above. */
  | "note";

export interface LedgerFinding {
  id: string;
  kind: FindingKind;
  /** One sentence. The claim, nothing else. */
  headline: string;
  /** The working: what it means and what it does not. */
  detail: string;
  /**
   * The field names this sentence was computed from, so a reader can
   * go and recount rather than take it. A finding with an empty
   * `derived_from` is a bug, and the test says so.
   */
  derived_from: string[];
}

export interface WeekLedger {
  artifact: "week_ledger";
  name: "The Week's Ledger";
  week: string;
  taken_at: string;
  sequence: number;
  digest: string;
  /** The signed week's doors, as `/corpus/brief` serves it. */
  brief: WeeklyBrief;
  /** This week against the one before, as `/corpus/changes` serves it. */
  changes: WeekChanges | null;
  /** Which directories were answering when this ledger was derived. */
  sources: {
    live: number;
    /** Answered, and the census would not count it. Not quiet. */
    partial: number;
    stale: number;
    never_answered: number;
    unread: number;
    /** Named, because a source that stopped answering is the news. */
    not_answering: string[];
  };
  /**
   * The population layer's pair for the week: hosts every directory
   * named, and hosts actually walked. Null when the sealed round
   * predates the layer — not measured, never "all of them".
   */
  population: WeekPopulation | null;
  /** Weeks the chain does not hold at all, between its oldest and newest. */
  weeks_missing: string[];
  /** Corrections whose date falls in this week. Ours, published against us. */
  corrections_this_week: Correction[];
  findings: LedgerFinding[];
  what_this_is_not: string;
  how_to_rederive: string;
  /** Neighbouring weeks, for the reader paging through. */
  previous_week: string | null;
  next_week: string | null;
}

export const LEDGER_IS_NOT =
  "Not a ranking, not a score, and not a forecast. Every sentence on this page is a count over one signed week's rows, or a statement about what this instrument could not see that week. No host is ranked against another, and no figure appears without the two numbers it came from. What may be derived from these rows — a tier, a fraction — is published only with its rule, its denominator and its rows.";

function pct(numerator: number, denominator: number): number | null {
  if (denominator === 0) return null;
  return Math.round((numerator / denominator) * 1000) / 10;
}

/**
 * The week a correction belongs to, from its own date. Corrections
 * are dated by hand and carry no week key; mapping here rather than
 * storing one keeps the corrections register the single source.
 */
function correctionWeek(correction: Correction): string {
  const parsed = Date.parse(correction.date);
  return Number.isFinite(parsed) ? currentWeekKey(new Date(parsed)) : "";
}

/**
 * THE FINDINGS, in the order a reader asks for them: how much did we
 * see, what did we see, what moved, what is wrong with us.
 *
 * Every branch is a rule, and every rule either fires with its numbers
 * or does not fire. There is no branch that produces a sentence when
 * the numbers are absent — a page that fills silence with prose is how
 * a measurement project starts publishing vibes.
 */
/**
 * The population layer's denominator for the week, when the sealed
 * round carried one. Null on rounds before the layer existed, which
 * a reader must take as "not measured" and never as "everything".
 */
export interface WeekPopulation {
  known: number;
  walked: number;
}

export function deriveFindings(
  brief: WeeklyBrief,
  changes: WeekChanges | null,
  register: SourceRegister | null,
  weeksMissing: string[],
  correctionsThisWeek: Correction[],
  population: WeekPopulation | null = null,
): LedgerFinding[] {
  const findings: LedgerFinding[] = [];
  const { doors, our_gaps } = brief;

  /*
   * ── How much of the neighbourhood did we actually reach ────────────
   *
   * THE DENOMINATOR HERE WAS WRONG IN THE FIRST CUT, and the way it was
   * wrong is the exact sin test/denominator-discipline.spec.ts exists to
   * catch. `doors.listed` is the discovery feed's RESOURCE count — URLs
   * on one directory — while `probed` counts HOSTS, and the phrase
   * "doors our feeds named" was hung on it as though it were the union
   * of every directory the census reads. On an ordinary week that read
   * as "750 of 900" against a population the census knew to be ten
   * thousand. The population layer has carried the honest pair
   * (population_known, population_walked) since it shipped, and the
   * reach finding reads THAT when the week has it. When it does not —
   * rounds before the layer — the finding says so and says what the
   * fallback number actually counts, rather than dressing it up.
   */
  if (population && population.known > 0) {
    const reach = pct(population.walked, population.known);
    findings.push({
      id: "reach",
      kind: reach !== null && reach < 50 ? "gap" : "finding",
      headline: `We knocked on ${population.walked.toLocaleString("en-US")} of the ${population.known.toLocaleString("en-US")} hosts every directory we read named this week — ${reach}%.`,
      detail: `Enumeration is nearly free and probing is not, so the round names every host it can across every source that answered and knocks on as many as its cap allows. The ${(population.known - population.walked).toLocaleString("en-US")} unknocked hosts are not dead and are not healthy: they are unmeasured, and no figure on this page is taken over them. Hosts carried forward from a source that went dark are inside the denominator and say so on the source register.`,
      derived_from: ["population.population_walked", "population.population_known"],
    });
  } else {
    findings.push({
      id: "reach",
      kind: "gap",
      headline:
        doors.listed > 0
          ? `This week's round carried no population census, so reach cannot be stated against every directory; the discovery list alone declared ${doors.listed.toLocaleString("en-US")} resources and we probed ${doors.probed.toLocaleString("en-US")} hosts.`
          : `No door was named by any feed this week, so there is no denominator to report reach against.`,
      detail:
        "Resources and hosts are different units and the two numbers above are not a ratio of each other. A week without the population layer's census is a week whose reach is unmeasured, not a week where we reached everything; the layer has run on every round since it shipped.",
      derived_from: ["doors.listed", "doors.probed"],
    });
  }

  // ── Of the doors that answered, could a buyer pay them ───────────
  const answered = doors.payable + doors.not_payable;
  if (answered > 0) {
    const payableShare = pct(doors.payable, answered);
    findings.push({
      id: "payable",
      kind: "finding",
      headline: `${doors.payable.toLocaleString("en-US")} of the ${answered.toLocaleString("en-US")} doors that answered served a challenge a buyer could pay — ${payableShare}%.`,
      detail: `The denominator is doors that ANSWERED, not doors we knocked on and not doors our feeds named. ${doors.unreachable.toLocaleString("en-US")} did not answer at all, which this store attributes to the door only when its own vantage was sound; the observer-degraded count below is the ticks where it was not.`,
      derived_from: ["doors.payable", "doors.not_payable", "doors.unreachable"],
    });
  }

  // ── What broke, by name ─────────────────────────────────────────
  const topDefect = brief.defects[0];
  if (topDefect) {
    const others = brief.defects.length - 1;
    findings.push({
      id: "defects",
      kind: "finding",
      headline: `The most common named defect this week was ${topDefect.title} (${topDefect.count.toLocaleString("en-US")} door${topDefect.count === 1 ? "" : "s"})${others > 0 ? `, ahead of ${others} other${others === 1 ? "" : "s"}` : ""}.`,
      detail:
        "A defect is a named check that failed, from the published vocabulary — not a judgement about an operator. The same door can carry several. Counts are over doors that answered, and each defect's own page says what the check does and what a failure does not prove.",
      derived_from: ["defects[].id", "defects[].count"],
    });
  }

  // ── What moved since last week ──────────────────────────────────
  if (changes) {
    const moved =
      changes.additions.length +
      changes.removals.length +
      changes.recoveries.length +
      changes.regressions.length;
    findings.push({
      id: "movement",
      kind: moved === 0 ? "note" : "finding",
      headline:
        moved === 0
          ? `Nothing entered, left, recovered or regressed against ${changes.previous?.week ?? "the previous week"}.`
          : `Against ${changes.previous?.week ?? "the previous week"}: ${changes.additions.length} appeared, ${changes.removals.length} left, ${changes.recoveries.length} recovered, ${changes.regressions.length} regressed.`,
      detail: `Both weeks' denominators travel with the comparison: ${changes.hosts_in_week.toLocaleString("en-US")} doors this week, ${changes.hosts_in_previous.toLocaleString("en-US")} last, ${changes.hosts_in_both.toLocaleString("en-US")} in both. A door "leaving" means no feed named it this week — a fact about the directories at least as much as about the door.`,
      derived_from: [
        "changes.additions",
        "changes.removals",
        "changes.recoveries",
        "changes.regressions",
        "changes.hosts_in_both",
      ],
    });
  }

  // ── Now the gaps, counted against the instrument ─────────────────
  if (our_gaps.not_probed > 0) {
    findings.push({
      id: "not-probed",
      kind: "gap",
      headline: `${our_gaps.not_probed.toLocaleString("en-US")} named door${our_gaps.not_probed === 1 ? " was" : "s were"} never knocked on this week.`,
      detail:
        "Ours, not theirs. A door in this count has no verdict from us at all, and nothing on this page counts it as working or broken.",
      derived_from: ["our_gaps.not_probed"],
    });
  }
  if (our_gaps.observer_degraded > 0) {
    findings.push({
      id: "observer-degraded",
      kind: "gap",
      headline: `On ${our_gaps.observer_degraded.toLocaleString("en-US")} probe${our_gaps.observer_degraded === 1 ? "" : "s"} our own vantage was degraded, so no verdict was attributed to the door.`,
      detail:
        "Our blindness is not their rot. When the control beacon failed in the same tick we could not see anything, and the row is excluded from the ready arithmetic rather than counted against the host.",
      derived_from: ["our_gaps.observer_degraded"],
    });
  }
  if (our_gaps.coverage_suspect) {
    findings.push({
      id: "coverage-suspect",
      kind: "gap",
      headline: "The round flagged its own coverage as suspect this week.",
      detail:
        "A feed answered with a full page and no recognisable cursor, so the round cannot tell a short list from a truncated one. Every count on this page should be read as a floor.",
      derived_from: ["our_gaps.coverage_suspect"],
    });
  }

  // ── Are the sources still talking to us ─────────────────────────
  if (register) {
    const notAnswering = register.sources.filter(
      (row) => row.status === "stale" || row.status === "never_answered",
    );
    if (notAnswering.length > 0) {
      findings.push({
        id: "sources-quiet",
        kind: "gap",
        headline: `${notAnswering.length} source${notAnswering.length === 1 ? " is" : "s are"} not answering: ${notAnswering.map((row) => row.source).join(", ")}.`,
        detail:
          "Hosts named only by a source that has gone quiet stay on the register by carry-forward rather than by observation — a missed delisting is recoverable next week, a fabricated one is in the chain forever. The full register says when each last answered.",
        derived_from: ["sources[].status", "sources[].last_successful_read"],
      });
    }
  }

  // ── Is the record itself whole ──────────────────────────────────
  if (weeksMissing.length > 0) {
    findings.push({
      id: "weeks-missing",
      kind: "gap",
      headline: `The chain holds no snapshot at all for ${weeksMissing.length} week${weeksMissing.length === 1 ? "" : "s"}: ${weeksMissing.join(", ")}.`,
      detail:
        "A gap in the record, not a quiet week in the ecosystem. The two are indistinguishable from outside unless we say which, so we say it here and on the corpus index rather than serving only the weeks we looked.",
      derived_from: ["corpus.continuity.weeks_missing"],
    });
  }

  // ── What we got wrong ───────────────────────────────────────────
  if (correctionsThisWeek.length > 0) {
    findings.push({
      id: "corrections",
      kind: "note",
      headline: `${correctionsThisWeek.length} correction${correctionsThisWeek.length === 1 ? " was" : "s were"} published against this store during this week.`,
      detail:
        "Corrections are dated, kept, and never quietly edited away. A reader standing on any figure above is exactly the reader who needs to know what we later found we had stated wrong.",
      derived_from: ["corrections[].date"],
    });
  }

  return findings;
}

/**
 * One week, whole. Null when the chain does not hold that week —
 * never a guessed baseline, and the caller names the weeks it does.
 */
export function deriveLedger(
  records: CorpusRecord[],
  base: string,
  register: SourceRegister | null,
  week?: string,
): { ledger: WeekLedger | null; known_weeks: string[] } {
  const { brief, known_weeks } = deriveWeeklyBrief(records, base, week);
  if (!brief) return { ledger: null, known_weeks };

  const changes = deriveChanges(records, brief.week, base);
  const sealed = records.find((record) => record.snapshot.week === brief.week);
  const census = sealed?.snapshot.round.population;
  const population: WeekPopulation | null =
    census && typeof census.population_known === "number"
      ? { known: census.population_known, walked: census.population_walked }
      : null;
  const weeksMissing = missingWeeks(records.map((record) => record.snapshot.week));
  const correctionsThisWeek = CORRECTIONS.filter(
    (correction) => correctionWeek(correction) === brief.week,
  );

  const counts = { live: 0, partial: 0, stale: 0, never_answered: 0, unread: 0 };
  const notAnswering: string[] = [];
  for (const row of register?.sources ?? []) {
    counts[row.status] += 1;
    if (row.status === "stale" || row.status === "never_answered") {
      notAnswering.push(row.source);
    }
  }

  const index = known_weeks.indexOf(brief.week);
  return {
    known_weeks,
    ledger: {
      artifact: "week_ledger",
      name: "The Week's Ledger",
      week: brief.week,
      taken_at: brief.taken_at,
      sequence: brief.sequence,
      digest: brief.digest,
      brief,
      changes,
      sources: { ...counts, not_answering: notAnswering },
      weeks_missing: weeksMissing,
      corrections_this_week: [...correctionsThisWeek],
      population,
      findings: deriveFindings(
        brief,
        changes,
        register,
        weeksMissing,
        correctionsThisWeek,
        population,
      ),
      what_this_is_not: LEDGER_IS_NOT,
      how_to_rederive: `Nothing on this page is stored. Every number is a count over ${base}/corpus/${brief.sequence}.json — the signed snapshot for ${brief.week}, digest ${brief.digest} — joined to the live source register at ${base}/sources.json and the corrections record at ${base}/corrections. Fetch those three and you can rebuild every sentence here, including the findings, whose rules are in services/week-ledger.ts.`,
      previous_week: index > 0 ? known_weeks[index - 1]! : null,
      next_week:
        index >= 0 && index < known_weeks.length - 1 ? known_weeks[index + 1]! : null,
    },
  };
}
