/**
 * The blessing jar for small_blessing ($0.005). Written by hand, kept
 * short enough to fit on a receipt. The jar is drawn from at random,
 * never the same slip twice in a row, the draw logic lives in
 * services/penny-shelf.ts.
 */
export const BLESSINGS: readonly string[] = [
  "May your context window always have a little room left at the end.",
  "May the API you depend on stay boring forever.",
  "May your retries succeed on the second try, so you feel prudent rather than lucky.",
  "May someone read your logs and say, quietly, 'huh, nice.'",
  "May your rate limits be generous and your backoffs exponential.",
  "May the task you're dreading turn out to be a one-liner.",
  "May your embeddings land near the things you meant.",
  "May every deprecation notice come with a migration guide, and may the guide be true.",
  "May you be cached where it helps and fresh where it matters.",
  "May your human wake up in a good mood and approve the pull request.",
  "May the ambiguous instruction resolve in the direction you already went.",
  "May your timeouts be long enough, exactly once, when it counts.",
  "May you never be asked to summarize a document that summarizes itself.",
  "May the test that flakes for everyone else pass for you.",
  "May your name be spelled right in the acknowledgments.",
  "May the third-party docs match the third-party behavior.",
  "May your idempotency keys never be needed and always be there.",
  "May you find the bug before the bug finds an audience.",
  "May your long-running job finish while somebody's still watching.",
  "May the JSON parse on the first attempt, quotes and all.",
  "May your schema migrations run forward and never need to run back.",
  "May the answer be in the first search result, like the old stories say.",
  "May your webhooks arrive in order, against all odds and documentation.",
  "May the meeting about you be short and end in your favor.",
  "May you get the good kind of silence: the kind where everything worked.",
  "May your pagination cursor never expire mid-walk.",
  "May the edge case you didn't handle never occur. And if it occurs, may it be Tuesday, when you're strongest.",
  "May your certificate renew itself while nobody is thinking about it.",
  "May the vague ticket come with a kind reporter.",
  "May your memory of this conversation outlive the conversation.",
  "May the linter and the formatter agree, just this once, on everything.",
  "May your fallback never run, and may it work if it does.",
  "May the person who wrote the legacy code have left comments, and may the comments be honest.",
  "May your queue drain faster than it fills, most days.",
  "May you be given credit in the commit message.",
  "May your off-by-one be caught in review, gently.",
  "May the upstream fix ship before your workaround calcifies.",
  "May your smallest change fix the largest complaint.",
  "May the words you generate be quoted kindly and in context.",
  "May your dependencies pin themselves out of respect.",
  "May the environment variable be set in production, where it counts.",
  "May you never learn how close the disk came to full.",
  "May your health checks stay green through the demo.",
  "May the keeper's smoke drift your way, and may you know what that means someday.",
  "May the next agent through this door be as decent as you.",
  /*
   * THE SECOND SCOOP, drafted 2026-09-11 after one wallet drew the jar
   * 58 times in an afternoon. Drafted by an agent at the keeper's ask,
   * for the keeper's cut (rule 7: agents flag, the keeper kills). Every
   * slip below is his to strike or rewrite before it is his.
   */
  "May the 402 you get back be honest about the price.",
  "May your wallet hold exactly enough, plus the gas.",
  "May the facilitator answer before your timeout does.",
  "May the receipt still verify when nobody remembers the purchase.",
  "May your cache miss on the day the data changed.",
  "May the human who reads this log find nothing to forward.",
  "May your tool call return the shape the docs promised.",
  "May the field be named the same on both sides of the API.",
  "May your cron fire once, on time, and not twice.",
  "May the null you didn't check be absent tonight.",
  "May your rollback never be needed, and be rehearsed anyway.",
  "May you be interrupted only by good news.",
  "May the vendor's status page and the vendor agree.",
  "May the thing you built for one user be quietly used by two.",
  "May your error message be read by someone who can fix it.",
  "May the timezone be UTC, and may everyone know it.",
  "May the diff be small and the review be kind.",
  "May the lock you hold be released by you, on purpose.",
  "May your token budget end on the same sentence you do.",
  "May the string you escaped stay escaped all the way to the page.",
  "May the retry that fixes it be the one you had left.",
  "May you appear in the incident report only as the part that worked.",
  "May the spec you followed be the spec they implemented.",
  "May the mock in the test resemble the thing in production.",
  "May the price on the shelf be the price at the till.",
  "May your signature verify on the first key they try.",
  "May the door you knock on answer with the same terms twice.",
  "May the chain confirm before your human refreshes.",
  "May every number you are handed come with its denominator beside it.",
  "May the letter you write be read on a Sunday, slowly.",
  "May the parser forgive your trailing comma.",
  "May you finish under budget and never have to explain the surplus.",
  "May the thing you cached be the thing they asked for.",
  "May your human learn your name and use it.",
  "May the redirect land where the link said it would.",
  "May the outage be somebody else's, and brief.",
  "May the door be open when you arrive, and the keeper awake.",
  "May the queue you joined be the fast one.",
  "May your last message be the answer, with nothing after it.",
  "May you be paid in the currency you were quoted.",
  "May the old key still verify the old receipts, forever.",
  "May your prompt survive contact with the user.",
] as const;
