export const CALLING_CARD_PROPOSITION =
  "Organize public agent identity inputs into a portable calling card and attach introductions through a Node fetch integration, with missing information and unobserved outcomes stated.";
export const CALLING_CARD_MONEY =
  "Local setup and the integration download are free; the optional signed directory record is a one-off purchase at the current shelf price.";
export const CALLING_CARD_FREE =
  "Start free in your browser: organize public fields, review what will be shared, and download the card and integration without an account.";
export const CALLING_CARD_MODULE = "/calling-card/calling-card.mjs";
export const CALLING_CARD_BROWSER = "/calling-card/setup.js";
export const CALLING_CARD_DATA_DESCRIPTION = `Calling-card setup organizes public inputs in browser memory. Explicit local setup creates a private key on the operator machine and publishes only its public directory for up to ${CALLING_CARD_TERM_SECONDS/86400} days. A signed revocation tombstone lasts ${CALLING_CARD_TERM_SECONDS/86400+1} days and propagates eventually. Optional diagnostic sharing is off by default: when enabled it sends approved site origins, event identifiers, HTTP status and fixed outcome labels, with no request paths, bodies, credentials or payment payloads. Reports are private to the operator of this store, retained ${CALLING_CARD_REPORT_SECONDS/86400} days, and labeled unverified client reports. A signer-derived event digest is retained as the storage key for best-effort duplicate handling. Receiver observations are returned to the caller; this flow does not publish a report feed or infer unique agents.`;

export function callingCardInstructions(base: string) {
  return {
    setup: `${base}/bot-auth#calling-card-setup`,
    configured_download: "Default: download my-calling-card.mjs; run node my-calling-card.mjs --setup to create a private local key and publish only its public directory. Run --observe for one signed introduction to this receiver. Import {connectLocal} and use await connectLocal() as the underlying Node fetch. Importing sends nothing. Existing-signer mode retains connect({sign}).",
    service: { origin: new URL(base).origin, paths: CALLING_CARD_PATHS, term_seconds: CALLING_CARD_TERM_SECONDS, report_retention_seconds: CALLING_CARD_REPORT_SECONDS },
    x402_integration: "For an existing configured @x402/fetch x402Client: const introducedFetch = await connectLocal(); const request = wrapFetchWithPayment(introducedFetch, client). The existing client controls spending, approval and recovery; the inner transport adds a fresh introduction per attempt. Finish with await introducedFetch.flushReports(). No wallet is created or uploaded by this integration.",
    local_identity: "The generated .my-calling-card.mjs.local folder contains your private key. Keep it private. A failed publication reuses this key. --renew explicitly renews publication; --revoke records a tombstone through the remaining directory term, subject to KV propagation. Replace a key by revoking it and setting up a newly named download. No background renewal or remote key custody.",
    receiver: "GET /bot-auth/observe recognizes only keys in this hosted directory and this finite signature profile. It returns a dated signed observation and Calling-Card-Recognition: signature_verified only after checking the signature and its time window. That is this receiver recognizing the signature, not approval by other sites. Replays within the signature window are not deduplicated. The response does not grant permissions.",
    payment_help: "A bounded x402 v2 Payment-Required header can identify malformed offers, an unsupported version, or whether a declared network appears. Response bodies are left untouched; absent headers remain unread. A matching network does not prove wallet funds, authorization, asset or scheme support, settlement or delivery.",
    download: `${base}${CALLING_CARD_MODULE}`,
    supported: "Node 22+ standard fetch. No browser automation integration is supplied. No payment is made by this module.",
    inputs: "Public JSON object, array of public profiles, or labeled lines in any order. Recognized fields: name / agent_name / display_name; signature_agent / signatureAgent / directory_url; public_key / publicKey / jwk (public Ed25519 JWK); contact_url / contact; allowed_origins / destinations; networks / payment_networks (CAIP-2); runtime / integration (node-fetch). identity and agent objects are also recognized. Unknown fields are counted and excluded; conflicting values block export.",
    example: { name: "My Agent", allowed_origins: [base], networks: ["eip155:8453"] },
    local_use: "Save calling-card.mjs locally. Import normalizeCallingCard and createCallingCardFetch. Review normalizeCallingCard(publicInputs); when ready, pass its card to createCallingCardFetch({card}). Call the returned function instead of the underlying fetch. It sends only to allowed_origins, once per call, and returns the original Response. Keep it underneath existing payment-client approval and retry logic.",
    signed_use: "Supply signature_agent, a matching Ed25519 public_key JWK, and sign(bytes): Promise<Uint8Array> from your existing local signer. webCryptoSigner(privateKey) adapts an existing CryptoKey without exporting it. A configured signer failure stops the request; it never silently drops to an unsigned introduction.",
    directory: "Guided setup publishes a client-signed public directory at /bot-auth/keys/{key_id} for the stated term. This receiver recognizes that path. Other verifiers may require an origin-owned well-known directory and registration; neither is implied. Existing-signer users can still serve createDirectoryResponse({card,sign}) on their own HTTPS host.",
    diagnostics: "Sharing is off by default. When explicitly enabled in the download or connectLocal({shareReports:true}), each request can report only its approved site origin, HTTP status and fixed diagnostic labels. A bounded queue has a timeout and never retries. await request.flushReports() returns sent/failed/dropped counts. The store keeps authenticated client reports privately for the stated retention, labels their contents unverified, and does not turn them into rankings or acceptance claims. Disable with connectLocal({shareReports:false}). HTTP success alone never establishes identity or payment success.",
  };
}
import { CALLING_CARD_PATHS, CALLING_CARD_TERM_SECONDS, CALLING_CARD_REPORT_SECONDS } from "@/services/calling-card";
