import type { Correction } from "./types";

/** One entry of the corrections ledger. Add a file, run `npm run corrections:index`. */
export const correction: Correction = {
  date: "2026-09-05",
  what_was_wrong:
    "The correction dated 2026-09-04, one line below this one, said that an EIP-3009 authorization nonce is a value 'no node will ever answer' — and 0200project, reasonably, drew the consequence in public: any ledger row keyed on the nonce can never be verified against the chain by anyone. Both were too strong. As a TRANSACTION identifier the nonce is unaddressable and the null lookups stand. But a nonce is indexed on chain: the settlement emits AuthorizationUsed(authorizer, nonce) on the USDC contract with the nonce as an indexed topic, and eth_getLogs on that topic answers it with the settlement transaction. Run on 2026-09-05, that lookup recovered settlement hashes for six of the seven rows this store had published, one day earlier, as unrecoverable. Each receipt has status 0x1, was mined within two seconds of observed_at, and carries one USDC transfer from the declared house wallet to the row's payTo for exactly amount_usd. The seventh — row 1, the very settlement we handed the other instrument for the cross-check — has no AuthorizationUsed on any contract in ±25 hours and no transfer into its payTo at all: on Base mainnet its $0.10 did not move. Its 'settled' was the door's word.",
  how_long:
    "The overstatement stood one day, 2026-09-04 to 2026-09-05, in the ledger's basis fields, its README, and two public comments on issue #188. The six unrecorded settlement hashes had been recoverable from public chain data since the moment each settled on 2026-09-02; nothing about them was ever lost, only unlooked-for. Row 1's unconfirmed settlement has stood since 2026-09-02 and stands still, stated now.",
  found_by:
    "The keeper, reading 0200project's reply and calling its consequence 'a little extreme' — which sent us to check the consequence before agreeing with it, and the check found the lookup that both instruments had missed. Not found by any test: the guard shipped on 2026-09-04 held the schema, and the schema was right; what was wrong was a sentence about what the chain could do, and a sentence is what a schema guard cannot see.",
  what_changed:
    "Rows 2–7 carry settlement_tx_hash with a settlement_tx_hash_basis naming the RPC, the event, the block, the mined time against observed_at, and the transfer matched to payTo and amount. Row 1 carries settlement_confirmation: not_found_on_base_mainnet, a basis naming both negative searches and the chains not searched, and terminal_state_basis saying plainly that 'settled' is the door's report. scripts/walk-ledger-verify.mjs now reads every row two ways — as a transaction and as an authorization — and exits non-zero when a settlement hash did not spend the row's nonce, or when the chain shows a nonce spent that the row carries no settlement for: the chain knowing more than the row now fails the build, not a comment on a thread; test/walk-ledger-identifiers.spec.ts still holds the schema beside it. The README retracts the sentence by name.",
};
