import type { Correction } from "./types";

export const correction: Correction = {
  date: "2026-09-14",
  what_was_wrong: "Settlement Reconciliation treated the largest same-owner Approval in a receipt as the selected transfer's observed ceiling, without establishing its spender or spending mechanism. It could override a correctly paired EIP-3009 fixed-value authorization, or invent an observed limit from a later approval. Its own receipt reader also lacked reported-chain, transaction identity, status and block/head checks. Wrong or incomplete provider evidence could become signed conclusions. The public report repeated the approval claim and described a missing ceiling as caller-supplied. A zero-match observation also contradicted its numeric count by saying exactly one transfer matched.",
  how_long: "Reproduced locally against the September 14 source after the separate authorization-pairing repair. First affected deployment and affected production artifacts are not established. This is synthetic evidence, not a claim that a live provider returned these faults.",
  found_by: "The keeper-requested buyer audit: signed synthetic receipts, unrelated approvals before and after transfers, malformed provider context, HTTP and both MCP payment dialects, and unauthenticated recipient reads. Tests were run against the unfixed implementation first. No live money was spent.",
  what_changed: "Current reconciliation only reports an observed limit for the selected canonically paired EIP-3009 transfer. Approval co-occurrence establishes no spending cap; declared caps remain declared. It uses the shared chain and receipt-context validators before signing. Invalid evidence is refused before settlement with actionable same-payment retry guidance; explicit null remains a dated not-found observation on an established chain and head. Public product and verification copy now explains those limits. Zero-match prose now agrees with the signed count, with missing, empty and reverted receipts tested separately. Historical chain_same_tx_approval records receive a correction warning outside the signed object; their original signed bytes are not rewritten. Recipient guidance supplies exact primary signature bytes and historical-key lookup, and separates a valid signature from truth of a claim. These are local repairs; deployment and live acceptance remain separate. Neither the RPC checks nor the signature establish consensus, finality or delivery.",
};
