import type { Correction } from "./types";

export const correction: Correction = {
  date: "2026-09-13",
  what_was_wrong: "Launch Check battery v3 classified a 2xx replay naming the original transaction as redelivery without comparing the goods, and a 2xx without that reference as fresh fulfillment without establishing new work. It credited server errors as correct refusals and described the first authorization as already settled before independently establishing that fact. The delivery note repeated those conclusions, including claims of money taken twice or product given away. The separate seller-named transfer read did not correlate this walk's exact authorization and amount; payment_attempt.settlement remained unknown even when stronger evidence was available.",
  how_long: "Reproduced locally from the September 13 source. Battery v3 dates from September 12; the transfer-only reading predates it. No production recipient count, affected signed-report inventory or first affected deployment was established.",
  found_by: "The keeper-requested buyer audit, using local seller responses, actual throwaway signatures, fixture RPC receipts with multiple authorizations, invalid UTF-8, capped streams and failure responses. These tests spent no live money.",
  what_changed: "Battery v4 binds a candidate receipt to the expected chain, transaction, canonical USDC contract, payer, nonce, recipient and exact atomic amount using the paired AuthorizationUsed and Transfer events. It reports confirmed, pending_finality or unresolved settlement separately from the broad transfer observation. Invalid chain/receipt identity or block evidence also prevents a confirmed broad-transfer label; unresolved reads do not earn a successful verification stage. Replay compares complete raw response bytes and publishes their digests and read limits: identical bytes establish byte recovery, changed bytes do not establish fresh fulfillment, and missing, empty, truncated or temporary-failure responses remain unresolved. A repeated transaction reference alone proves neither payment nor delivery. A fresh challenge establishes no second charge; the walk signs no new authorization and either presentation may have been the first settlement. The guide, note and specimen now state these limits. Current instrument caveats accompany the versioned defect vocabulary without rewriting its definitions or claiming its historical mappings establish these defects. test/launch-payment-binding.spec.ts and test/launch-replay-evidence.spec.ts reproduce the boundaries, serve and verify the signed evidence, and reject tampering. Historical signed records retain their bytes. This repair does not change the general Settlement Attestation product's older nonce-only classifier, verify a linked artifact's truth or usefulness, or establish live-chain behavior.",
};
