import type { Correction } from "./types";
export const correction: Correction = {
  date: "2026-09-28",
  what_was_wrong:
    "Open for Business, the weekly issue for sellers, read every counter under the month's key and printed the month to date as 'this month' beside a week's title. Two issues went on the shelf that way (2026-W38 and 2026-W39), so a buyer of the second paid for numbers that mostly repeated the first. Worse than the window, three sentences claimed what the counters could not see. The section on who reads the record counted any host with two or more reads as a repeat reader and printed 6,774 of 6,775 hosts as read more than once, with none of the 96,089 reads referred from a host itself and about fourteen reads a host: an unnamed fetcher walking every page, classed as an agent because the machinery table did not know it. The concentration histogram had been built on 2026-09-21 to tell exactly that walk from a return, names the weekly as a consumer in its own comment, and the weekly never read it. The number of the week and the went-well lead said a re-check over a week old came 'from someone other than the buyer'; the gap line under the same section says age says when, not who. And the lead on refusals named three reasons and left the largest bucket, 235 of 501 filed as 'other', unmentioned, most of it 400s keyed by a code and about no field at all.",
  how_long:
    "From the shelf opening on 2026-09-18 until this correction, across two published issues and every draft on the desk.",
  found_by:
    "The keeper, pasting the desk's draft of 2026-W40 back and asking what could be honed. The 6,774 of 6,775 was the shape that gave it away, as the 287 on one field had on the refusal desk a week earlier.",
  what_changed:
    "Every writer the issue reads now bumps a week twin beside the month (lib/kv-keys.ts: a period is a month or an ISO week, and a week key gets its own prefix so the whole-prefix scans never see it), and the issue reads its own week and prints the days it counted, from the day the twins went live. A week the twins never saw is laid as not read and is never pressed onto the shelf. The reader section reads the histogram, publishes hosts at five and ten reads and the mean, and calls a walk a walk when nine in ten hosts sit at two or more reads; the operator clause appears only when a read was referred from the host itself. The number of the week stops at the age. The refusal lead names the 'other' bucket and the code that led it, and its disclosure line is derived from the census rather than asserted. The MCP handshake census goes through the machinery table the way refusals do. The settles are put against the 402s issued, per channel, as a floor and never a rate. Tests in test/week-twins.spec.ts prove each writer lands its twin, and test/open-for-business.spec.ts seeds a fixed week and witnesses each sentence red without the fix. The two issues already on the shelf are left as published, under the keeper's take-down lever; nothing on them is restated here as the week's figure, because a month to date is not a week and the twins did not exist to count one.",
};
