import type { Correction } from "./types";
export const correction: Correction = {
  date: "2026-09-15",
  what_was_wrong:
    "The decline desk published a fault verdict its own rule said was wrong, and published the rule directly beneath it. Every reading of a missing-input refusal ended 'the same thing from DIFFERENT clients means the requirement is not discoverable from the header alone, and that would be ours to fix in the challenge' — and readReason, which takes one reason string and cannot see a second client, had already hardcoded fault: buyer on the line above. The escalation could not fire however many clients hit the same wall. On 2026-09-15 the desk read 27 outside declines, all of them 'theirs', 0 house, while local:input_missing:tx_hash had been refusing three separate implementations at settlement_attestation for five consecutive days and local:input_missing:host had done the same at spot_check. The underlying cause was ours the whole time: required_params went out in the 402's JSON body and in a nonstandard bazaar discovery extension, and a stock x402 client reads neither — it decodes PAYMENT-REQUIRED, signs an accepts entry and retries. A buyer who did exactly what the protocol says was refused before the gate and then counted on our own page as careless.",
  how_long:
    "The missing-input readings and their unappliable rule shipped 2026-09-04. The discoverability gap is older: required_params has lived in the unpaid response body since the input-taking doors opened. The visible five-day run of one client (python-httpx/0.28.1, 2026-09-11 through 2026-09-15) is a floor and not a count — the decline index began 2026-09-06 and the raw scan is capped at 3000 rows, so how long it had been walking into this wall before that is not recoverable.",
  found_by:
    "The keeper, reading the desk and asking what was worth double-clicking. No outside party reported it, which is the uncomfortable half: the clients this turned away had no way to tell us, and the page they would have shown us said it was their fault.",
  what_changed:
    "Two mechanisms, one for the cause and one for the blindness. (1) The requirement now rides the challenge every client already decodes: buyRouteDescription puts 'REQUIRES ?tx_hash= on the paid request' ahead of the pitch, in the description field, which in x402 v2 belongs to top-level ResourceInfo rather than to the PaymentRequirements entries a client echoes back — so it cannot widen the deep-equal that mints requirement_mismatch, and a test walks every menu item asserting each required parameter appears inside ROUTE_DESCRIPTION_CAP. The body, the extension and the probe rule are untouched; this is a fourth place to find it, in the first place anyone looks. (2) The desk now takes the count it kept asking for: readDeclines builds clients_by_reason and escalateSharedReasons rewrites the fault to 'ours' when two or more distinct clients hit the same missing-input code, naming them on the page so the reader can check the verdict rather than trust it. That count deliberately includes the noise floor — a conformance crawler that read our challenge and could not find a required input is evidence about the challenge whatever it intended to spend — while the demand columns beside it stay clean, and the house is excluded because family reading our own challenge proves nothing. readReason itself is unchanged and still stateless, because metrics.ts writes the keeper's page off it with one event in hand; the escalation runs where the whole window is. The rail and v1-envelope readings, which say 'DIFFERENT clients' for reasons that are not faults we own, are annotated with the count and keep their verdict.",
};
