import type { Correction } from "./types";

export const correction: Correction = {
  date: "2026-09-14",
  what_was_wrong: "Settlement Attestation independently matched a USDC transfer and a nonce anywhere in the receipt. It discarded the authorization's payer when deciding correspondence. A batch could therefore produce a signed SETTLED observation for a transfer belonging to a different authorization. Battery v2's binding could also claim authorization_nonce when the requested payer, recipient or amount failed to match. With only a nonce supplied, the report could select the first unrelated transfer or silently choose between multiple authorizers using the same nonce.",
  how_long: "Reproduced locally from the September 13 source. Battery v2's explicit binding field dates from September 11; the independent nonce/status check predates that field. The first affected deployment and production artifact count were not established.",
  found_by: "The keeper-requested buyer audit: signed observations over adversarial batch receipts, wrong-authorizer and wrong-term cases, ambiguous nonces, malformed events and a signature-tampering check. These local tests spent no live money.",
  what_changed: "Battery v3 uses one shared canonical-USDC AuthorizationUsed/Transfer pairing reader for both the general observation's status and binding, also used by Launch Check. The nonce must identify one authorizer event immediately followed by its Transfer from that authorizer, with every supplied transfer field matching that pair. Unknown ordering, duplicate candidates and mismatches establish no binding. A payer distinguishes different authorizers' reuse of the same nonce. Signed binding.evidence records the reason and readable pair, including atomic amount and receipt positions. Discovery inputs, the practice guide and /attestation describe these limits and the older battery's caveat. The existing binding fixture was corrected from transfer-before-authorization and abbreviated event data to Circle's event order and ABI shape. test/attestation-authorization-pairing.spec.ts reproduces the failures and checks signatures against tampering. Historical signed bytes remain unchanged. This is a trusted-RPC interpretation of canonical USDC events, not a consensus proof, deployed-proxy audit, delivery claim, or repair of the separate purchase and settlement reconciliation readers. Live acceptance remains separate.",
};
