import type { Correction } from "./types";

/** One entry of the corrections ledger. Add a file, run `npm run corrections:index`. */
export const correction: Correction = {
  date: "2026-09-04",
  what_was_wrong:
    "The MCP door took a buyer's arguments, validated the arguments of a handful of items, and carried a short list of fields into fulfillment. Every other field an item needs to know what it is being asked about \u2014 `url`, `address`, `tx_hash`, `tx_hashes`, `wallet`, `digest`, `mandate` and the rest \u2014 was read off the wire and dropped before the goods were made. Three shapes came out of that one defect. good_buyer and launch_check each produced and SETTLED a signed artifact about the empty string: at $0.99 and $5.00 respectively, both on 2026-09-04: each probed \"\", folded the unreachable result into a signed reading exactly as they are built to do, and took the money \u2014 so the buyer holds two real, correctly signed observations about no endpoint on earth. attestation_bundle minted a certificate over an empty sheaf, settled, and then threw on its way out, leaving money moved, a certificate issued and a 500 in the buyer's hand, recoverable only via /trust if they knew to look. passport_refresh and provenance_check threw before the settle, so those cost nothing \u2014 the deliver-first rule holding \u2014 but answered a paying customer with an error page roughly half the time. The HTTP door was never affected: it had the whole map and the whole set of refusals.",
  how_long:
    "From the day the MCP buy shelves opened until 2026-09-04. No purchase over MCP of any affected item was ever correct, and the store cannot say how many there were beyond the first buyer's, because the argument that would have identified the subject is the argument that was dropped. Making the buyer whole for the two settled artifacts is the keeper's hand, not this fix's.",
  found_by:
    "The first outside agent to shop the MCP shelf with a real wallet, reporting all three shapes with the amounts and the item ids, on the day they happened. Nothing in here found it: the store's own MCP tests bought the items whose arguments the door DID carry, and the one spec that came near it wrote the reason down \u2014 \"service_audit takes its url later, so it reaches the challenge instead\" \u2014 and treated that as a fact about the test rather than as the defect it was.",
  what_changed:
    "Both doors now read one argument map and one set of pre-payment refusals out of src/lib/purchase-args.ts; the MCP door's forked copies of both are deleted, so an item that grows a field gets it on both doors or on neither. test/mcp-carries-the-buyers-arguments.spec.ts derives its guard from the published input schema rather than from a list: for every item on every MCP shelf, removing a required argument must change what fulfillment is handed, and both doors must build byte-identical input from the same values. A second derived guard buys nothing and asserts that no shelf issues payment terms for a call missing a required argument. Dropping one item out of the shared map fails all of them.",
};
