import type { Correction } from "./types";

/** One entry of the corrections ledger. Add a file, run `npm run corrections:index`. */
export const correction: Correction = {
  date: "2026-09-04",
  what_was_wrong:
    "The weekly walk published not_ready verdicts against doors that were payable, because two of its checks read every chain as if it were Ethereum or Solana. payto-payable resolved any unrecognised CAIP-2 namespace to the EVM branch: an XRPL classic address is base58 in a band that sits inside the Solana window, so a correct XRPL payTo was reported as \"a base58 Solana address ... no buyer on this rail can pay this offer\", and Stellar and Algorand addresses, being base32, matched nothing and were reported as neither an address nor a name service. amount-atomic applied the USDC atomic-units rule to XRPL issued currencies, which the ledger itself denominates in decimals, and told those doors that \"0.01\" underprices by a factor of a million. In round 2026-W36, 63 of 1,089 hosts walked failed payto-payable and 56 failed amount-atomic; every one of those 56 also offered a chain the desk could not read. The verdicts were signed and published against named hosts.",
  how_long:
    "One published round. The three checks were promoted from advisories into the v2 verdict on 2026-08-30. Round 2026-W35, walked 2026-08-24, carried zero such failures; round 2026-W36, walked 2026-09-01, carried 65, of which 61 hosts had read ready the week before. Before the promotion the same misreads existed but rode as advisories, visible and not verdict-changing. For the week the verdicts stood, the affected hosts\u2019 passport pages showed not_ready and their README chips refused to render, since the chip publishes names only on the ready side. Round W36 stays in the chain as walked; the corrected instrument publishes fresh rows on the next walk beside it.",
  found_by:
    "The keeper asked how to double-check an operator who had replied \"I forsure know mine works\". Running our own preflight against his door returned 7 of 8 checks passing and one failure, and the failure was ours: his XRPL address read as a Solana one. Reading the round for the same signature found 63 hosts, 3 of them on our own outreach list — we had written to operators about doors our instrument had misjudged.",
  what_changed:
    "familyOf now names xrpl, stellar and algorand and returns \"unknown\" instead of defaulting to evm, and readPayTo gained a fourth verdict kind, unknown-network, whose payable is null: not judged, never failed. l3bChecks threads that null through, keeps unjudged entries out of the verdict, and prints them beside the pass so the reading names what it did not judge. amount-atomic now judges amounts only on the rails this store settles on and has tested, EVM and Solana, and names every other rail's amount beside the pass rather than ruling on it — a first draft exempted only XRPL issued currencies and kept judging Stellar and Algorand on the same assumption that had just been wrong, and the rule-52 guard below caught it before it shipped. transfer-method-signable no longer calls a non-EVM method unbuildable, since the methods it knows are EVM signature standards. Rule 52 already forbade all of this; its enforcement walked only KV reads, so test/bounded-read-honesty.spec.ts now also walks the readers that judge strangers, asserting that no unrecognised chain can ever produce a \"no\". test/value-checks.spec.ts holds the three real doors that were misjudged, by their actual addresses, and holds a genuinely broken EVM door still failing both checks.",
};
