import type { Correction } from "./types";

/** One entry of the corrections ledger. Add a file, run `npm run corrections:index`. */
export const correction: Correction = {
  date: "2026-09-05",
  what_was_wrong:
    "The passport chip — the one artifact this store asks operators to paste into their README — drew its own text on top of itself. Two runs shared the top baseline with no width budget between them, so on any host with a tier the label ran through the freshness and date: `SCVD PASSPORT · INDETERMINATE` overprinted `FRESH • 2026-09-01`, illegibly, and the two words a reader could pick out of the wreck contradicted each other. On the line below, the hostname ran through a verify URL printed at the right edge. The share card that a pasted passport link unfurls into had the matching problem of kind rather than of overlap: a 5x7 hand set enormous on a blank field, which reads as a terminal dump rather than as a document. The keeper, looking at a live chip: \"why would anyone post this on their readme.\"",
  how_long:
    "The chip has rendered at /badges/passport/{host}.svg since 2026-08-21 and gained the tier on its face on 2026-09-02; from that date any host with a tier — which is every census-observed host — drew the overlap. Three days, on every chip anyone had pasted, plus the passport page's own To Share block. The share card has looked as it did since 2026-09-02. No verdict was wrong: this is a defect in what we published, not in what we observed, and it is in this ledger because the ledger is where things this store put in front of people that were not fit to be there get dated.",
  found_by:
    "The keeper, opening a live chip for bykaranteli.com and the share card on the same passport page.",
  what_changed:
    "SVG text does not wrap and a Worker cannot measure a glyph, so every label in badge-svg.ts had been placed at hand-picked coordinates and hoped. A character count could not have caught it either — the old fit was host.slice(0, 34), and WWW.EXAMPLE.COM is nowhere near the width of illinois.io. So there is now a width estimate by glyph class (textWidth) that errs WIDE on purpose, a fitter that truncates to a stated budget (fitToWidth), and the chip's geometry lives in CHIP_LAYOUT with every budget DERIVED from it rather than typed twice. test/chip-geometry.spec.ts walks every drawn run against its budget for the inputs that actually break a layout — the longest registrable hostname, the widest possible caps, every freshness word, every tier — so an edit that moves the seal without moving the budget fails in the suite instead of on somebody's front page. The chip was then redrawn as a letterpress label: one hairline frame with squared corners, a struck seal, tracked small caps over the host over one record line, and printer's inks rather than a dashboard's greens. The tier's word no longer rides on the face when it is `indeterminate` — that is a statement about how many rounds we hold, not about the door, and it had been the loudest thing on a chip whose own decision was READY. The share card was rebuilt on a coverage buffer with a 6x9 engraved alphabet, proportional metrics, and a certificate's frame, rules and seal; it encodes as a sixteen-step indexed PNG so the type is inked rather than tiled.",
};
