import type { Correction } from "./types";

export const correction: Correction = {
  date: "2026-09-14",
  what_was_wrong: "Purchase recovery matched the original authorization and a transfer independently, so a different transfer in the same batch could establish paid status. Settlement Reconciliation could label a selected transfer no_discretion because the same payer used an authorization elsewhere in the receipt. General EVM Settlement Attestation also lacked receipt transaction, reported-chain and block/head validation; malformed provider answers could become signed settlement conclusions. The bundle reader treated a missing result as not found and let duplicate response IDs overwrite evidence.",
  how_long: "Reproduced locally against the September 14 source before this repair. The first affected deployment, affected production artifacts and live buyer impact were not established.",
  found_by: "The keeper-requested follow-through: the actual purchase-recovery alarm, signed reconciliation outputs, malformed RPC observations, source-reversion controls, and HTTP/MCP purchase tests with local settlement fixtures. No live money was spent.",
  what_changed: "Both reconciliation readers now use the shared canonical-USDC AuthorizationUsed/Transfer pair. Recovery requires the original payer, nonce, recipient and atomic amount on that pair; signed reconciliation additionally checks the selected transfer's receipt position. General Settlement Attestation battery v4 validates EVM transaction identity, reported chain, recognized receipt status and safe block/head data; each bundle member is validated and missing or duplicate batch answers are refused. Explicit null remains a dated not-found observation, while invalid provider evidence cannot become a claim about money. New receipt refusals tell HTTP and both MCP payment dialects that this request submitted no payment, explain same-payment retry, leave temporariness unknown and do not invent a verification URL. Previously settled purchase failures retain their separate recovery handling. Current artifact descriptions point to this correction; historical signed bytes remain unchanged. The canonical-USDC interpretation remains dependent on the observed RPC evidence and recognized token event ordering, not a consensus proof or a guarantee about delivery. Separate Approval cap attribution and the Settlement Reconciliation reader's own RPC context are not repaired by these changes. Deployment and live acceptance remain separate from this local evidence.",
};
