import type { Correction } from "./types";
export const correction: Correction = {
  date: "2026-09-16",
  what_was_wrong:
    "Two facts the store computed and then threw away on every decline. (1) THE PAYER. A settle has written a payer row since the till opened; a decline never carried one, because gateSignals reads headers and query while the signer lives inside the base64 payload. So isHouseTraffic met every decline with no wallet to match — the third time this file has recorded that exact blindness, after CV's field run and the cold read — and the desk could not say WHO had been turned away. The store learned a buyer's address only if they got through. Worse: the store's own RECEIVING address is not in house-wallets.json (that file registers wallets that SPEND here), so a payment signed from the till's own payTo booked as OUTSIDE DEMAND, and the facilitator refusing it `self_send_not_allowed` was the only way the keeper ever heard. (2) THE DISAGREEMENT. describeMismatch has always built the whole report — which offer came closest, which field differs, and BOTH VALUES — and the 402 carried it to the buyer. The books kept a reason code with a field NAME in it and nothing else, so fifteen `local:requirement_mismatch:amount` rows from one client inside 48 seconds could not be told from a client that was one unit conversion away. AND a reading shipped the day before, on 2026-09-15, told the keeper to 'read the payer off the row before anything else' — advice for a field that did not exist.",
  how_long:
    "Since the decline instrument began. The payer has been absent from every decline row ever booked; the mismatch detail since describeMismatch was written. The bad advice in the self_send_not_allowed reading was live for one day.",
  found_by:
    "The keeper, asking where in /admin to find three specific declines. The answer was that two of the three questions could not be answered from the desk at all, and that the reading pointing at the payer was pointing at nothing.",
  what_changed:
    "Both doors now book both facts. payerFromPaymentHeader runs at the decline site on the HTTP gate and the MCP door, so the payer rides EventSignals into isHouseTraffic and onto the row; mismatchSignal flattens the first FieldMismatch to three bounded strings (field, we_offered, you_sent) and books that beside it. isHouseTraffic gained a second wallet test: a payer equal to any of the store's payTo addresses on any rail is house, read off the secrets rather than through lib/payments so the metrics writer takes no import cycle. The direction of that error is the argument, the same way round as the HOUSE_AGENTS test: counting a self-send as house REMOVES it from the organic figures and understates the store, where counting it as a stranger inflates them. The desk grows a payer column and a disagreement column, and both read 'not recorded' rather than 'none' on rows older than this change, because the books cannot support the stronger claim. The self_send_not_allowed reading is corrected to name the classification rule and what genuinely remains to check, and its test now pins the new wording so the old advice cannot come back.",
};
