import type { Correction } from "./types";
export const correction: Correction = {
  date: "2026-09-15",
  what_was_wrong:
    "A facilitator refusal arrives in two parts: a short reason CODE and a free-text message. The 402 got both — payment-gate's firstSuspect reads `${reason} ${message}` and can tell a buyer their wallet is probably short — but recordPaymentDecline was handed the code alone, and event.note kept only that. So the buyer got the diagnosis and the books got a stub. CDP's `invalid_payload` is overloaded across at least three different failures (a malformed payload, an already-settled nonce, and a verify-time revert from an underfunded wallet), and every reading in readReason written to tell them apart — revert, insufficient, expired, valid_after, replay — keys on words that existed only in the message. Those readings were unreachable from any booked row. The visible cost: a payment offered at /api/buy/hello and declined `invalid_payload` paged the keeper as 'UNCLEAR, needs a read — the signature did not verify', which is the catch-all at the bottom of readReason, while the 402 that same buyer received may already have named their balance. The $21 revert of 2026-09-01 got a reading written for it that could never fire.",
  how_long:
    "Since the decline instrument began booking a reason string. The revert reading added 2026-09-01 and the balance and replay readings older than it were all written against text the books never carried, so the gap is at least as old as those rules and probably as old as the desk.",
  found_by:
    "The keeper, forwarding a live 'UNCLEAR, needs a read' alert and asking what to make of it. The alert was the evidence: its own wording is the catch-all reading, and the store had already sent the buyer better words than it kept for itself.",
  what_changed:
    "The message is now read down to ONE of a closed set of classes (revert, replay, insufficient, expired, valid_after) and rides the booked reason as a bounded suffix in the existing `+payload:` style — `invalid_payload+verdict:revert`. It is never booked verbatim: vendor English rewords without notice, and slugging it would put an unbounded string family into by_reason, which is the mistake local:sdk_threw exists to avoid. The class names are deliberately the words readReason's existing rules already match on, so a suffixed row routes to the reading written for it and no rule changed; a test pins each class to its reading, so renaming one without the other fails the build. Where the facilitator's message earns a class it OUTRANKS our own field note, because readReason checks `+payload:` before it checks revert and an advisory ERC-1271 signature note riding on an underfunded payload would otherwise bury the balance behind a signature fault. Both doors and both stages were changed together — the HTTP gate and the MCP door, verify and settle — because one door getting the good instrument is the failure this file has already recorded once.",
};
