import type { Correction } from "./types";
export const correction: Correction = {
  date: "2026-09-21",
  what_was_wrong:
    "The avoidable-400s desk counted machinery as buyers, and /open-for-business published the total as a sentence about agents: 'N agents were refused before paying this month.' recordInputRefusal asked nothing about who was refused — no house check, no reader class, nothing — while every other recorder in the same file skips the house, and the settle signal beside it says why in its own comment: 'the family's own wallets would be the loudest voice in a signal this quiet.' In refusals the loudest voice is louder still. The month's figure was 1,053, of which 287 malformed ONE field at one door and 178 and 167 did the same at two others; a buyer does not malform the same field 287 times, and a census walking every door on a loop does. StillOS-payability-census/1.0 writes 'measurement, no payment attached' into its own user-agent and was counted in that number, because the machinery table held 'census-probe' and this client calls itself a census without the probe. The same lesson had already been learned twice on the decline desk next door, in the corrections of 2026-09-15 and 2026-09-16, one of which states the principle in the words that fit here exactly: no money was ever going to come from a conformance walker. It did not cross the gap between two desks in one file.",
  how_long:
    "From the day the desk opened until this correction. The published sentence carried the mixed figure for the whole of that period, and the keeper read it off the live page as a usability crisis, which is what surfaced it.",
  found_by:
    "The keeper, pasting the live desk back — the avoidable-400s table and the decline desk one above the other. The decline desk below it named the very clients the table above had swallowed, which is what made the odd shape legible: 287 refusals on a single field beside a bot that announces it will never pay.",
  what_changed:
    "recordInputRefusal now classes every refusal with readerClass, the same classifier the receipt desk already used, and writes to one of two maps: refusal_organic for agents and browsers, refusal_machinery for self-identified machinery. Machinery is KEPT and published rather than dropped — whether a linter can satisfy an input contract is evidence about the challenge, and this store does not hide a denominator it has — but it is stated as its own number and excluded from the sentence about agents. 'census' joined the machinery table as a whole-word job name, generalising the 'census-probe' entry that nearly matched and therefore matched nothing. The old `refusal` map is retired rather than migrated: it mixed the two irreversibly, so every figure it produced is withdrawn rather than restated, and the desk reads the new pair from the day of this correction. Two tests in test/buyer-signals.spec.ts pin both directions and fail the build if either slips: one asserts a census and a linter refused at the same door land on the machinery map while a python-httpx client lands on the buyers', and one asserts readerClass calls a self-named census machinery, which is the near-miss that let this through. What this still cannot say is how many DISTINCT clients sent the rest; the rows keep no client string, where the decline desk does, and that remains unfixed and named here rather than implied.",
};
