import type { Correction } from "./types";

/** One entry of the corrections ledger. Add a file, run `npm run corrections:index`. */
export const correction: Correction = {
  date: "2026-09-06",
  what_was_wrong:
    "The correction dated 2026-09-05, describing the machinery built after two operators corrected two of this desk's notes in one afternoon, said of the re-read: 'one press knocks again on every door a note went to and lays the current instrument's reading beside the row the note was drafted from.' It did not lay it beside that row. It laid it beside whatever row the LATEST weekly census held for that host, which is the same row only until the next census runs and then is a different fact entirely — after a walk, the comparison was this week's census against a live probe, a staleness check on the census rather than a check on the note. Worse, the disagreement rule compared one bit: ready against not-ready. A note that named `payto-payable` at a door now failing `amount-atomic` read AGREE, because both readings are not-ready — so the exact failure mode the re-read was built to catch, a note whose named finding no longer holds, was the one it was blind to. Both flaws shipped in the same commit as the sentence describing them, and the page repeated the sentence on the keeper's own screen.",
  how_long:
    "One day, 2026-09-05 to 2026-09-06, in the ledger entry, in the section heading and prose on /admin/outreach, and in the code itself. No wrong note was sent because of it; what it cost is a day in which the desk's own audit could have called a wrong note quiet and nobody would have known. The re-read had been pressed by hand a small number of times in that window, all against the census round that produced the notes, where the two comparisons happen to coincide.",
  found_by:
    "The keeper, asking where the press was and then what happens when it disagrees — which made the desk read its own comparison aloud and find that it did not do what its own correction said. Not found by any test: the specs asserted the rule as written, and a test that pins the wrong rule passes forever.",
  what_changed:
    "The claim a note makes is now frozen on the ledger the moment the note goes out (OutreachEntry.claimed — the reading it was drafted from, its week, and the rails the door offered then), by the wire at send and by the stamp routes for hand delivery, and it is never overwritten. The re-read is held against THAT, and a note stamped before the field existed says on its own row that it is falling back to the census. The comparison is on the checks the note named, not on the readiness bit. The call is three ways: `agree`; `ours`, DERIVED from the retraction ledger when every check the note named has since been retracted, which needs no judgement and drafts the correction email itself; and `look`, everything else, which stays the keeper's because healed-since and ours are the same shape from outside a door. And it no longer waits for a press: auditSweep rides the half-hourly tick, five doors a pass, each door at most once a day, and pages the keeper with the drafted correction attached. It still sends nothing — rule 30 does not relax because a cron is in front of it. test/outreach-audit.spec.ts pins all three calls, the daily floor, and the drafted correction; test/outreach-desk-hygiene.spec.ts pins the freezing.",
};
