import type { Correction } from "./types";
export const correction: Correction = {
  date: "2026-09-21",
  what_was_wrong:
    "Every discovery document this store publishes handed an agent a `buy_url` that, on the twelve input-taking doors, refuses the purchase it advertises. The requirement sat in `required_params` directly beside it — a SIBLING field the reader has to notice, cross-reference, and then act on by rewriting the URL itself. An agent that does the obvious thing with a field called buy_url gets a signable 402 and then a refusal before the gate. The bounded price-discovery row at /api/catalog/v1 was worse: it carries buy_url and has no required_params at all, so nothing on that document said the door needed anything. Four places already named the rule — the resource description, two extensions, the 400's repair block — and the reading on the decline desk still had to end 'the requirement is not discoverable where they are looking', because the one field an agent ACTS on was still the wrong URL.",
  how_long:
    "As old as the input-taking doors. The catalog has published a bare buy_url beside required_params since those items opened; the 2026-09-06 pass added required_params to the catalog precisely because seventeen items named a price and a buy_url and never the input, and it added the sentence rather than fixing the URL.",
  found_by:
    "Following the decline desk's own instruction to its end. The PAYMENT-REQUIRED header was fetched live from all twelve doors and carried the requirement every way x402 allows, so the publishing was ruled out — and x402 v2 has nowhere left to put it: ResourceInfo is {url, description, mimeType, serviceName, tags, iconUrl} and PaymentRequirements carries no input schema, both read off the installed @x402/core types. A simulated stock client then showed the whole shape in two runs: probe `?host=example.com`, sign, retry, 200 and delivered; probe the bare door, sign, retry, 400 and no money moved. The buyer path works. What fails is the URL the store hands out.",
  what_changed:
    "A URL that does not need the rule read. `buy_url_template` is the same door with its required inputs already in place as `<name>` slots, in the identical form the 402's required-inputs extension already uses for retry_url_template — a test pins the two to the same string, so no document teaches a different URL. It is emitted on every item in the full catalog and the compact input contract, equal to buy_url where nothing is required, for the reason routes/catalog.ts gives for required_params: one key, one type, never telling 'absent' from 'needs nothing'. On the bounded /api/catalog/v1 row, which has a size ceiling and no required_params, it is emitted ONLY where it differs, so its presence is itself the signal that the bare door will not serve. The refusal carries it too: a query-door 400 now hands back the URL to retry instead of only the field names, and its next_action says to buy that URL. The checkout steps say to buy the template, not the bare door. BUY_URL ITSELF IS UNTOUCHED AND STAYS BARE: a bare probe of it must keep answering 402 or every indexer and directory checker reads the door as dead, which is the regression of 2026-07-26 and again of 2026-09-11 — a test asserts both halves, that the template differs and that the bare probe still quotes.",
};
