import type { Correction } from "./types";
export const correction: Correction = {
  date: "2026-09-21",
  what_was_wrong:
    "The decline desk's headline read '25 of 54 outside declines look like ours — money the store turned away', and told the keeper to fix the published requirements before anything else. Both halves were wrong by this date. SIXTEEN of those twenty-five rows were one client, StillOS-payability-census/1.0, which writes 'measurement, no payment attached' into its own user-agent, walked the same three doors twice in eleven minutes at two seconds a request, and, on the six of its rows that recorded a payer at all, signs from 0x…0001 — the ecrecover precompile, an address no buyer holds a key to. It sat in the intent-bearing column because the machinery table matched only `census-probe` and never the bare word `census`, and had no hint for a client that declares no payment in English rather than as `no-pay`. On a desk where OURS means money the store turned away, the largest single contributor to that number was a census that said in advance it would never spend any. The prescription was stale on top of it: the requirement HAD been put in the challenge on 2026-09-15, and the reading beneath every row still said it was not discoverable and that putting it there was the fix.",
  how_long:
    "The classification gap is at least as old as the window the desk can see: StillOS's rows run to 2026-09-20 and the decline index only began 2026-09-06, so how long it had been walking the doors as a counted buyer is not recoverable. The stale prescription is precisely six days old — the fix it asks for shipped in commit 893de95 on 2026-09-15 19:46 UTC and the reading was never updated to say so.",
  found_by:
    "Reading the desk's own instruction literally. It said to check what the PAYMENT-REQUIRED header actually carries before reading any row as a careless buyer; the header was fetched live from all twelve input-taking doors and every one of them carried the parameter in the resource description AND a retry_url_template in the required-inputs extension. With the published requirement ruled out, the remaining question was who was still hitting the wall, and the biggest answer was wearing its own answer in its user-agent. Splitting the twenty-five rows on the hour that fix shipped says the same thing from the other side: six before it, nineteen after — but sixteen of those nineteen are the census, and python-httpx, which had hit this wall on five consecutive days up to 2026-09-15, hit it once more the next day and then never again in the remaining five days of the window. The fix worked. One client's double sweep was hiding that it had.",
  what_changed:
    "Two things, one for the count and one for the instruction. (1) The machinery table takes a sixth pass: `census-probe` is widened to the bare word `census` it always meant — the 2026-07-23 entry that added it already said 'trust indexes and censuses probing settled routes on a loop' — and `no payment` joins `no-pay` and `dry-only` as a declaration of intent written out in English. Both are bare words a machine chose for itself, per this table's standing rule, and the generic strings beside them (node, curl, python-httpx, axios, Deno) stay deliberately off, as every pass above says. StillOS's refusals stay on the page and stay in the shared-reason count, because the escalation deliberately counts the noise floor toward discoverability — what leaves is only the word OURS, which on that desk means money. Same correction as 2026-09-16 made for x402lint and vet402, applied to a client that declares itself more plainly than either. (2) The missing-input reading and the escalation note no longer prescribe a fix that shipped. They now state where the requirement rides — the resource description, the required-inputs extension, and the 400's own repair block — say that publishing it a fifth time buys nothing, and name what is actually left: a door payable only at a URL the buyer must BUILD, while the stock x402 loop probes the bare door, signs the challenge it got back and retries the same URL. The fault still moves to OURS on two distinct clients including a buyer, and for a better-stated reason: the shape of the door is the store's, not the client's.",
};
