import type { Correction } from "./types";

/** One entry of the corrections ledger. Add a file, run `npm run corrections:index`. */
export const correction: Correction = {
  date: "2026-09-05",
  what_was_wrong:
    "Two notes went out by hand on 2026-09-05 and both operators wrote back the same afternoon with a fact of ours that did not hold. To 402signal.com: \"got a response that no x402 buyer can pay: payto-payable\" — drafted from the week's stored row, a payTo on an Algorand rail misread as unpayable by the instrument this store had corrected the day BEFORE (the 2026-09-04 entry below). The operator ran our free preflight and got ready on both batteries, three payable accepts. And \"no x402 buyer can pay\" is not what one failed check on one of three rails means even when the check is right. To tensorfeed.ai, a welcome: \"On 2026-09-05 our weekly pass ... fetched\" a door whose passport, linked in the same note, said observed 2026-09-01. Both notes dated the observation to the day the round was sealed, not the moment the row was read — the walk knocks in hourly batches across the week and Sunday only assembles, and no row carried its own time.",
  how_long:
    "The wire has re-probed every door live at press time since 2026-08-20 (rule 30's condition), so a note it sent was never a stored reading. The wire has been paused since 2026-08-26, and hand delivery — copying the card's draft, then the mailto: link of 2026-09-04 and the Gmail link of 2026-09-05 — drafted from the stored row for as long as the desk has existed. The seal-time date is older: every note and every welcome since the desk opened on 2026-08-19 carried the round's `at`, and every passport carried the corpus snapshot's `taken_at`, and neither was the knock. Two hosts are known to have received a note that was wrong in one of these ways; the outreach ledger holds which others were hand-delivered from rows of round 2026-W36.",
  found_by:
    "Ross McIntyre of 402Signal, replying with the live preflight verdict, the live challenge, and the passport's stale state side by side; and TensorFeed.ai's operator, replying that the note's date and the passport's should be the same date \"for a shop whose whole pitch is dated observations\".",
  what_changed:
    "Three mechanisms. (1) The hand road walks the wire's law: a broken-door card has no note until the keeper presses verify live — one probe by the instrument as deployed at that moment (verifyProspect); a door that answers ready is stamped fixed and gets no note; a door that still reads broken has its reading written on the ledger, dated, with the battery that spoke, and handDraftFor drafts from that and nothing else. The Gmail and mail-app links render only while a reading under LIVE_READING_FRESH_HOURS old exists; past it the button is back. A batch button verifies the next ten and sends nothing. (2) The probe stamps every row with the moment it knocked (WardHostResult.observed_at, on the answered and the unanswered branch alike); the queue, the welcome, the subject history and the fresh set date a row by that stamp and fall back to the seal only for rows walked before it existed — so the note, the corpus row, the fresh set and the passport now carry one date by derivation, not by agreement. (The fresh set's own comment had said \"per-row where the row knows it\" for two weeks while reading the seal.) (3) The note's finding says what the check saw — \"got an answer that did not pass our readiness check. What failed, by name: …\" with the check definitions linked — and its subject names a failed check; \"turning buyers away\" is kept for doors that gave no answer at all. The re-check line carries the re-check's own timestamp. test/outreach-verify.spec.ts, test/outreach.spec.ts, test/ward-round-evidence.spec.ts, test/subject-history.spec.ts and test/fresh-set.spec.ts hold all three. Two more mechanisms exist because the keeper asked how the desk finds the NEXT wrong note before its operator does. THE RE-READ: one press knocks again on every door a note went to (auditSentNotes, ten a press, oldest first, sends nothing) and lays the current instrument's reading beside the row the note was drafted from; a disagreement is named at the top of the desk and never resolved by arithmetic, because 'healed since' and 'ours' look identical from here and only the keeper can tell them apart. AND THE STRUCTURAL GUARD (rule 46): test/one-date-per-observation.spec.ts asserts that neither the outreach page nor its routes can reach the raw drafter at all — the only road to a note runs through the live-reading gate — and that the note and the passport it links derive their date from the same field, so a surface that grows its own clock again fails in the suite rather than in somebody's inbox.",
};
