import type { Correction } from "./types";

/** One entry of the corrections ledger. Add a file, run `npm run corrections:index`. */
export const correction: Correction = {
  date: "2026-09-05",
  what_was_wrong:
    "The service-window check on /api/verify, shipped 2026-08-24 as 'layer 3' and described as closing the stolen-retired-key gap, answered `in_service` on the strength of the date the artifact carries — and that date is the one field a holder of a stolen retired key chooses. A receipt minted today, dated inside a retired key's window, citing a real settlement from that window and signed with that key, read `in_service` with prose that placed it inside the window as if the placement had been checked. The check caught the careless forgery (dated after retirement) and passed the careful one. The store's key log, which the /attestation page offered as the Bitcoin-anchored half of the answer, bounds when a handover was ANNOUNCED and says nothing about when any artifact the retired key signed came to exist; the settlement transaction inside each receipt gives a not-before and nothing gave a not-after.",
  how_long:
    "From 2026-08-24, when the window check shipped with that description, to 2026-09-05: twelve days on every certificate verify response, and on the /attestation page's framing of the key log for the whole time it has been anchored.",
  found_by:
    "navigatorbuilds, an outside reader on the x402 settlement-attestation-receipt thread (coinbase/x402 PR 46), replying to CV's description of the anchor log: the log's existed-by bounds the announcement, not the artifact, so 'a key that appears having already issued artifacts is a compromise' is only decidable if the artifact's own existence is bounded, and the honest verdict without that is 'signed by a key that was once current'. Not found by any test here: test/key-window.spec.ts forged the shape the check catches and never the shape it does not.",
  what_changed:
    "Every certificate's signed bytes are now digested and submitted to OpenTimestamps by the hourly sweep (services/certificate-anchors.ts), upgraded to a Bitcoin attestation, and the block height is read off the completed proof. /api/verify serves it as `existence`, with the digest compared against artifact_hash on the same response and a five-state verdict that never collapses: a bound on or before the key's retirement is 'signed while the key was current'; a bound after it is 'issue time unproven' — the shape of every receipt anchored on backfill AND of a stolen retired key, which the artifact alone cannot tell apart, and the verdict says so instead of guessing; no bound yet is 'unproven', never a pass. The artifact's own date is not an input to that verdict. Receipts minted before 2026-09-05 were anchored on backfill and carry the weaker verdict permanently. The /attestation page's line on chains now says what the per-receipt bound does and does not add. test/certificate-anchors.spec.ts holds the walk, the proof parse, the block lookup, and the verdict on each key state, including the careful forgery.",
};
