import type { Correction } from "./types";

export const correction: Correction = {
  date: "2026-09-15",
  what_was_wrong: "Wallet Claims could locate a paid certificate after client state was lost, but could not return its original Spot Check observation. A buyer needed the old payment or private recovery handle despite having proved ownership of the paying wallet. OpenAPI also required a wallet response field that the route never returned; the actual field is address. Existing private-status and original-payment recovery could say completed while retaining the old instruction to give the keeper a week.",
  how_long: "Observed in the September 15 live buyer acceptance run. The first affected deployment was not established.",
  found_by: "The keeper-requested buyer recovery audit after a cancelled response and a local test-journal overwrite. Expert reconstruction of an already-used payment recovered the observation without another charge; that was not a normal buyer recovery pass.",
  what_changed: "After wallet proof, POST /api/claims accepts an optional cert_id and reads the original retained transaction response. It checks payer, network, transaction, certificate and original signature, returns current evidence for the same human order, and honors recorded resolutions before old goods. Reads neither settle nor mint. Unknown and other-wallet certificates have the same refusal. Missing historical goods remain explicit gaps with keeper-contact guidance; unavailable storage tells the buyer to repeat a fresh wallet claim without paying. All three recovery paths now derive human-order status, message, completion time and evidence from the same response as the order page, so completed goods no longer carry the queued message. The list, OpenAPI, skill and guide explain the two-step recovery. Local signed-fixture tests cover configured EVM and Solana rails, HTTP and both MCP payment profiles, privacy, damaged records and original bytes. These checks do not establish live recovery on every rail or restore records never retained; release and live acceptance are separate.",
};
