import type { Correction } from "./types";

export const correction: Correction = {
  date: "2026-09-18",
  what_was_wrong:
    "Two days after the 2026-09-16 correction that moved the probe's verb out of four door probes and into one file, this store's operator posted a list of five doors on the x402 specification thread (x402-foundation/x402#3249) as serving no payment challenge, and two of the five — stableenrich.dev/api/fullenrich/people-search and stableupload.dev/api/upload — serve a flawless x402 v2 challenge to POST and a 405 to GET. Both were probed with GET. Both also carry a valid MPP challenge (WWW-Authenticate: Payment) and an agent-identity challenge on the same 402, so a reader of the x402 channel alone would have called them 'no payment metadata' one layer up as well. This is the exact defect the 2026-09-16 entry corrected — a GET-only probe false-negativing a POST-only, spec-compliant door — except this time it was published on the spec's own thread rather than mailed to one operator, and a stranger caught it in seven minutes.",
  how_long:
    "The deployed free preflight, the census and the standing watch were already resolving the verb when the list was posted: re-run today, both doors come back ready, probe_method POST by fallback, protocols_spoken x402 and mpp. So the list was not produced by the corrected instruments as deployed, and this ledger does not claim to know which instrument or hand produced it — the keeper's note is the record of that. What IS established: a fifth GET-only reader of strangers' 402s survived the four-probe fix. The paid single-door audit's surface reads (services/surface-reads.ts) re-read the probed door's 402 as a bookend and read the resource URL the challenge names, and both sent GET and only GET since they shipped on 2026-09-02, so on a POST-only door the battery found the challenge with POST and the section beneath it filed the bookend as 'answered 405 with no parseable challenge' on the signed artifact. Sixteen days for that reader; two days between a correction that said 'the law lives in one file that all four door probes call' and the discovery that there were five. Rows and artifacts sealed before today stand as history; nothing is re-signed.",
  found_by:
    "minia2auk, replying on x402-foundation/x402#3249 seven minutes after the list went up, with both doors re-curled: GET 405, POST 402 with resource.method POST in the payload. They also proposed the distinction this store had been missing in its own vector — that a wrong verb deserves its own state, NOT_EXERCISED, rather than a seat in the same bucket as a broken door — and named the second layer, the MPP challenge on the same response, that a single-channel census would have missed. The operator re-verified both doors independently before accepting either finding. The 2026-09-16 entry's found_by was an operator writing in privately; this one is a reader of the public thread, which is the direction rule 52 predicts these will keep coming from until the instrument stops making the claim.",
  what_changed:
    "FOUR THINGS, each a mechanism. (1) The fifth reader goes through the shared method law: services/surface-reads.ts now takes the battery's own ProbeMethodReading from the paid audit, the 402 bookend re-asks the SAME question the battery asked (same URL, same method, no fallback — a bookend that asks a different question cannot say whether the price moved), the resource URL read starts from the battery's method with the one bounded second look, and a method refusal on either is marked method_refused and rendered 'unreadable' with the gap named as ours — never 'silent', which is the state that means 'found, names no price' and was the false accusation in row form. The two document reads (llms.txt, OpenAPI) go through the same function with the fallback off, the shape discovery/host-probe.ts already uses, so the file carries no hard-coded verb at all. (2) The guard stops trusting its own list. test/bounded-read-honesty.spec.ts adds surface-reads.ts to the enumerated probes AND adds a sweep over every source file under src/: any file that reads a PAYMENT-REQUIRED header off a response it fetched with a hard-coded GET, without the shared law, fails the build. The enumeration was wrong twice (three, then four, then five); the sweep is the half that does not depend on anybody remembering. (3) The vector gets the state minia2auk proposed. checks_vector rows on a method_unresolved report are now not_exercised with refused_methods, instead of not_reached blocked_by status-402 — which was the prior output for an EMPTY check list and named, as the blocker, a check that had never run either. A reader dumping vectors into buckets had every reason to file that beside a real status-402 failure; now the row says 'this check was never asked, the door named the verb it wants, the gap is ours.' The OpenAPI schema carries the fourth state. (4) The offline census script (scripts/x402-census.mjs) stops excluding declared non-GET rows and stops saying 'one GET per host': it probes every row through the public preflight, which resolves the verb, tallies probe_method from each report, keeps method_unresolved out of the graded denominator, and prints a methodology line that says what was actually sent. Guarded by test: a POST-only door's bookend is read with POST and only POST; a refused bookend renders unreadable and never silent; a method_unresolved vector is all not_exercised with no blocked_by; and a POST-only door carrying both PAYMENT-REQUIRED and WWW-Authenticate: Payment reports both wires off the one response the method law resolved.",
};
