import type { Correction } from "./types";
export const correction: Correction = {
  date: "2026-09-28",
  what_was_wrong:
    "The 2026-09-21 correction said every discovery document now carried buy_url_template, and the reading printed beside every missing-input decline since then has said a row dated after that fix 'is a client that had a buyable URL in every document it read'. Six documents did not carry it, and they are the ones a buyer is standing on when it decides to pay: the ladder rungs a free preflight or look hands back (launch_check, service_audit, conformance_watch, standing_watch, passport_refresh — every one of them wants ?url=), the paid examples on /how-it-works and the deeper reads on /doors (spot_check, the_case_file, provenance_check and the watches, all input-taking), the agent line in every room footer that sells a deeper read, the markdown twin of every item page, whose line marked buy printed the bare door and left the input to the house-rules prose four lines down, and the answer-engine copy at /what. Each of those handed an agent the bare door — a signable 402 followed by a refusal before the gate — while the desk's reading told the keeper the buyer had been given the right URL everywhere.",
  how_long:
    "The rungs, the room footers, the markdown twin and /what have named the bare door since each surface opened; the gap in the 2026-09-21 claim is seven days old. The keeper's second reading of the decline desk on 2026-09-28 found no real payment turned away — the missing-input volume was one full-catalog sweeper on a fifteen-to-forty-five-minute loop plus the conformance walkers the machinery table already names — so no money is known to have been lost to this, and the finding is the claim, not a sale.",
  found_by:
    "Reading the desk's own instruction to its end again: it says to check what the buyer was actually handed before reading any row as a careless buyer, and the 2026-09-21 check had fetched the challenge and the catalog and stopped there. Fetching the rest of what a buyer reads between a free probe and a paid retry found the six.",
  what_changed:
    "The rung helper every ladder rides (ladderRung) emits buy_url_template beside buy_url, so the preflight, the look and the operator's statement carry it at once; /how-it-works, /doors and the room rungs emit the same key from the same function, and the room footer's agent line quotes the template rather than the bare door. The markdown twin's buy line IS the template now, with a required-inputs line naming each slot and the bare door as the thing that quotes and refuses; an input-less item's twin is byte-identical to before. /what's long-tail answers name the template. buy_url stays bare everywhere, for the probe rule. THE MECHANISM: test/buy-url-you-can-buy-at.spec.ts walks all six — the rungs by name, both JSON documents, every room that sells a deeper read, the markdown twin of every input-taking item and the answer copy — and asserts each carries the identical string the catalog and the 402's retry_url_template already carry, so the next document that names a buy door without its slots is the next red test rather than the next decline.",
};
