/**
 * THE LEDGER, ONE FILE PER ENTRY (2026-09-04).
 *
 * Every correction used to be one object in one array in one file, and
 * every fix prepends to it — so two sessions landing fixes on the same
 * day collided on the same line twice in one afternoon, each conflict
 * a merge of two twenty-line prose objects by hand. The array is now
 * derived: one file per entry in this directory, an index generated by
 * scripts/corrections-index.mjs, and a test that fails the build when
 * a file exists that the index does not list. Two sessions adding two
 * entries touch two files and one generated line each; a conflict, if
 * it still happens on the index, is resolved by running the script.
 */
export interface Correction {
  /** ISO date the correction shipped. */
  date: string;
  /** What the store said or did that was not true. Plainly. */
  what_was_wrong: string;
  /** How long it was live, when we can say. Never softened. */
  how_long: string;
  /** Who found it. Outside eyes get named as outside eyes. */
  found_by: string;
  /**
   * THE REQUIRED HALF: what changed so it cannot recur silently. A
   * mechanism, not an intention. "We will be careful" is not a fix.
   */
  what_changed: string;
}
