import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {newAttempt,recordRoundTrip,assessAttempt,collectSolanaReceipt,collectEvmReceipt,checkSubmission} from './lib/buyer-run-evidence.mjs';
const prior=JSON.parse(fs.readFileSync('research/deployment-boundary-2026-09-11/responses.json')).find(r=>r.paid);
const proof=JSON.parse(fs.readFileSync('research/deployment-boundary-2026-09-11/proofs.json')).find(r=>r.id===prior.id);
function complete(){const a=newAttempt({id:'small_blessing',fulfillment:'instant'},prior.args,prior.offer.network);Object.assign(a,{quoted_terms:[{accepts:[prior.offer]}],payment_submitted:true,chain_result:{state:'confirmed',matches_quote:true},store_result:{http_status:200},artifact:structuredClone(prior.body),verification_result:structuredClone(proof.verification),product_review:{inputs_preserved:true,promised_good_received:true},recipient_understanding:{state:'reviewed',understands:true}});return a;}
test('all buyer evidence allows a pass',()=>assert.equal(assessAttempt(complete()).state,'pass'));
test('HTTP success without chain evidence remains incomplete',()=>{const a=complete();a.chain_result={state:'unobserved'};assert.equal(assessAttempt(a).state,'incomplete');});
test('valid receipt with unreviewed good remains incomplete',()=>{const a=complete();delete a.product_review;assert.equal(assessAttempt(a).state,'incomplete');});
test('unreviewed recipient cannot pass',()=>{const a=complete();a.recipient_understanding={state:'unreviewed'};assert.equal(assessAttempt(a).state,'incomplete');});
test('wrong subject fails despite valid cryptography',()=>{const a=complete();a.product_review.inputs_preserved=false;assert.equal(assessAttempt(a).state,'fail');});
test('tampered signature fails',()=>{const a=complete();a.artifact.signature='00'.repeat(64);assert.equal(assessAttempt(a).state,'fail');});
test('a replacement signed result is not original verification',()=>{const a=complete();a.verification_result.signed_payload='{}';assert.equal(assessAttempt(a).state,'fail');});
test('first paid request is not a retry even when journaled before sending',async()=>{const a=complete();a.round_trips=[];const wire=Buffer.from(JSON.stringify({accepted:prior.offer,payload:{}})).toString('base64');const req=new Request('https://example.com/buy',{headers:{'PAYMENT-SIGNATURE':wire}});await recordRoundTrip(a,req,new Response('{}',{status:200}),new Date().toISOString());assert.equal(a.unexpected_retries,0);await recordRoundTrip(a,req,new Response('{}',{status:200}),new Date().toISOString());assert.equal(a.unexpected_retries,1);assert.equal(assessAttempt(a).state,'fail');});
test('EVM collector rejects transfer to wrong recipient',async()=>{const original=globalThis.fetch;try{globalThis.fetch=async()=>Response.json({result:proof.receipt});const a=complete();a.selected_terms={...prior.offer,payTo:'0x'+'00'.repeat(20)};const r=await collectEvmReceipt(a,'https://fixture.invalid');assert.equal(r.matches_quote,false);}finally{globalThis.fetch=original;}});
test('Solana collector requires correct mint and both owner balance changes',async()=>{const original=globalThis.fetch;try{const a=complete();a.artifact={signed_payload:JSON.stringify({settlement_tx:'fixture-signature',payer:'buyer'})};a.selected_terms={asset:'USDC-mint',payTo:'seller',amount:'1000'};const b=(owner,amount)=>({owner,mint:'USDC-mint',uiTokenAmount:{amount}});const result={transaction:{signatures:['fixture-signature']},meta:{err:null,preTokenBalances:[b('buyer','2000'),b('seller','0')],postTokenBalances:[b('buyer','1000'),b('seller','1000')]}};globalThis.fetch=async()=>Response.json({result});assert.equal((await collectSolanaReceipt(a,'https://fixture.invalid')).matches_quote,true);result.meta.postTokenBalances[1].uiTokenAmount.amount='999';assert.equal((await collectSolanaReceipt(a,'https://fixture.invalid')).matches_quote,false);result.meta.postTokenBalances=[];result.meta.preTokenBalances=[];assert.equal((await collectSolanaReceipt(a,'https://fixture.invalid')).state,'unobserved');}finally{globalThis.fetch=original;}});

test('known invalid signature fails even while recipient review is pending',()=>{const a=complete();a.artifact.signature='00'.repeat(64);a.recipient_understanding={state:'unreviewed'};assert.equal(assessAttempt(a).state,'fail');});
test('body-only quotes are retained when optional header is absent',async()=>{const a=complete();a.quoted_terms=[];await recordRoundTrip(a,new Request('https://example.com/buy'),Response.json({accepts:[prior.offer]},{status:402}),new Date().toISOString());assert.equal(a.quoted_terms[0].accepts[0].amount,prior.offer.amount);});

test('spending guard counts unresolved submissions and refuses automatic repayment',()=>{const a=complete();a.payment_submitted=false;const priorAttempt=complete();priorAttempt.selected_terms=prior.offer;const wire=Buffer.from(JSON.stringify({accepted:prior.offer})).toString('base64');const amount=Number(prior.offer.amount)/1e6;assert.throws(()=>checkSubmission(a,[priorAttempt,a],wire,amount),/ceiling/);assert.equal(checkSubmission(a,[priorAttempt,a],wire,amount*2).amount,prior.offer.amount);a.payment_submitted=true;assert.throws(()=>checkSubmission(a,[a],wire,amount*2),/second payment/);});
test('spending guard rejects a rail or offer it did not quote',()=>{const a=complete();a.payment_submitted=false;const wire=accepted=>Buffer.from(JSON.stringify({accepted})).toString('base64');assert.throws(()=>checkSubmission(a,[a],wire({...prior.offer,network:'wrong'}),1),/unknown selected/);assert.throws(()=>checkSubmission(a,[a],wire({...prior.offer,payTo:'wrong'}),1),/not retained/);});
