#!/usr/bin/env node
/**
 * Writes src/store/corrections-ledger/index.ts from the directory:
 * one import per entry file, newest date first, then filename
 * descending so the order is total and stable. The array the store
 * serves is this list; a file the index does not name is a correction
 * the store does not publish, which is why test/corrections-ledger
 * holds the two equal.
 */
import { readdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const dir = join(here, "..", "src", "store", "corrections-ledger");

export function ledgerFiles(names) {
  return names
    .filter((n) => /^\d{4}-\d{2}-\d{2}-.+\.ts$/.test(n))
    .sort((a, b) => (a < b ? 1 : a > b ? -1 : 0));
}

export function renderIndex(files) {
  const ids = files.map((f, i) => `c${i}`);
  const imports = files.map((f, i) => `import { correction as ${ids[i]} } from "./${f.replace(/\.ts$/, "")}";`).join("\n");
  return `// GENERATED by scripts/corrections-index.mjs — do not edit by hand.
// Add a file to this directory and run: npm run corrections:index
import type { Correction } from "./types";
${imports}

export const CORRECTIONS: readonly Correction[] = [
${ids.map((id) => `  ${id},`).join("\n")}
];
`;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const files = ledgerFiles(readdirSync(dir));
  writeFileSync(join(dir, "index.ts"), renderIndex(files));
  process.stdout.write(`corrections-ledger/index.ts: ${files.length} entries\n`);
}
